import { Chapter } from './types';
import Colors from './colors';

export const chapters: Chapter[] = [
  {
    id: 'mod-1',
    title: 'Cardiovascular I',
    subtitle: 'HTN & HF Workhorses',
    icon: 'Heart',
    color: Colors.chapterColors[0],
    parts: [
      { id: 'm1-p2', title: 'ACE Inhibitors & ARBs', description: 'Lisinopril, Enalapril, Losartan, Valsartan, Irbesartan', drugIds: ['m1-1', 'm1-2', 'm1-3', 'm1-4', 'm1-5', 'm1-6', 'm1-7'], questionCount: 10 },
      { id: 'm1-p3', title: 'Thiazide & Loop Diuretics', description: 'HCTZ, Chlorthalidone, Furosemide, Bumetanide, Torsemide', drugIds: ['m1-8', 'm1-9', 'm1-10', 'm1-11', 'm1-12', 'm1-13'], questionCount: 10 },
      { id: 'm1-p4', title: 'Beta-Blockers (HTN, HF, CAD)', description: 'Metoprolol, Carvedilol, Atenolol, Propranolol, Bisoprolol', drugIds: ['m1-14', 'm1-15', 'm1-16', 'm1-17', 'm1-18', 'm1-19', 'm1-20'], questionCount: 10 },
      { id: 'm1-p5', title: 'MRAs & ARNI', description: 'Spironolactone, Eplerenone, Sacubitril/Valsartan', drugIds: ['m1-21', 'm1-22', 'm1-23'], questionCount: 8 },
      { id: 'm1-p6', title: 'Calcium Channel Blockers', description: 'Amlodipine, Diltiazem (high-yield CCBs)', drugIds: ['m2-24', 'm2-25'], questionCount: 8 },
    ],
  },
  {
    id: 'mod-2',
    title: 'Cardiovascular II',
    subtitle: 'Lipids & Thrombosis',
    icon: 'Activity',
    color: Colors.chapterColors[1],
    parts: [
      { id: 'm2-p1', title: 'Statins (HMG-CoA Reductase Inhibitors)', description: 'Atorvastatin, Rosuvastatin, Simvastatin, Pravastatin', drugIds: ['m2-1', 'm2-2', 'm2-3', 'm2-4', 'm2-5', 'm2-6'], questionCount: 10 },
      { id: 'm2-p2', title: 'Non-Statin Lipid Agents', description: 'Ezetimibe, Fenofibrate, PCSK9, Niacin, Icosapent Ethyl', drugIds: ['m2-7', 'm2-8', 'm2-9', 'm2-10', 'm2-11'], questionCount: 10 },
      { id: 'm2-p3', title: 'Antiplatelets', description: 'Aspirin, Clopidogrel, Ticagrelor, Prasugrel', drugIds: ['m2-12', 'm2-13', 'm2-14', 'm2-15'], questionCount: 8 },
      { id: 'm2-p4', title: 'Anticoagulants', description: 'Warfarin, Apixaban, Rivaroxaban, Dabigatran, Heparins', drugIds: ['m2-16', 'm2-17', 'm2-18', 'm2-19', 'm2-20', 'm2-21'], questionCount: 10 },
      { id: 'm2-p5', title: 'Antianginals & Nitrates', description: 'Nitroglycerin, Isosorbide, Amlodipine, Diltiazem, Ranolazine', drugIds: ['m2-22', 'm2-23', 'm2-24', 'm2-25', 'm2-26'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-3',
    title: 'Endocrine & Diabetes',
    subtitle: 'Metabolic & Hormonal Agents',
    icon: 'Droplets',
    color: Colors.chapterColors[2],
    parts: [
      { id: 'm3-p1', title: 'Insulin Overview (Basal & Bolus)', description: 'Glargine, Detemir, Degludec, Lispro, Aspart, NPH, Regular', drugIds: ['m3-1', 'm3-2', 'm3-3', 'm3-4', 'm3-5', 'm3-6', 'm3-7'], questionCount: 10 },
      { id: 'm3-p2', title: 'Metformin & Oral Agents Overview', description: 'Metformin, Pioglitazone', drugIds: ['m3-8', 'm3-9'], questionCount: 6 },
      { id: 'm3-p3', title: 'SGLT2 Inhibitors', description: 'Empagliflozin, Dapagliflozin, Canagliflozin', drugIds: ['m3-10', 'm3-11', 'm3-12'], questionCount: 8 },
      { id: 'm3-p4', title: 'GLP-1, DPP-4, Sulfonylureas', description: 'Semaglutide, Dulaglutide, Sitagliptin, Glipizide, Glimepiride', drugIds: ['m3-13', 'm3-14', 'm3-15', 'm3-16', 'm3-17', 'm3-18', 'm3-19', 'm3-20', 'm3-21'], questionCount: 12 },
      { id: 'm3-p5', title: 'Thyroid Agents', description: 'Levothyroxine, Methimazole, PTU', drugIds: ['m3-22', 'm3-23', 'm3-24'], questionCount: 8 },
      { id: 'm3-p6', title: 'Adrenal Steroids (Systemic Corticosteroids)', description: 'Prednisone, Prednisolone, Methylprednisolone, Dexamethasone', drugIds: ['m3-25', 'm3-26', 'm3-27', 'm3-28', 'm3-29'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-4',
    title: 'CNS & Psych',
    subtitle: 'Mind & Mood Medications',
    icon: 'Brain',
    color: Colors.chapterColors[3],
    parts: [
      { id: 'm4-p1', title: 'Antidepressants I (SSRIs, SNRIs)', description: 'Sertraline, Escitalopram, Fluoxetine, Venlafaxine, Duloxetine', drugIds: ['m4-1', 'm4-2', 'm4-3', 'm4-4', 'm4-5', 'm4-6', 'm4-7'], questionCount: 10 },
      { id: 'm4-p2', title: 'Antidepressants II (TCAs, Atypicals)', description: 'Amitriptyline, Nortriptyline, Bupropion, Mirtazapine, Trazodone', drugIds: ['m4-8', 'm4-9', 'm4-10', 'm4-11', 'm4-12'], questionCount: 10 },
      { id: 'm4-p3', title: 'Antipsychotics (Typical & Atypical)', description: 'Quetiapine, Aripiprazole, Risperidone, Olanzapine, Haloperidol', drugIds: ['m4-13', 'm4-14', 'm4-15', 'm4-16', 'm4-17'], questionCount: 10 },
      { id: 'm4-p4', title: 'Anxiolytics & Sedatives', description: 'Alprazolam, Lorazepam, Diazepam, Zolpidem, Hydroxyzine', drugIds: ['m4-18', 'm4-19', 'm4-20', 'm4-21', 'm4-22', 'm4-23', 'm4-24'], questionCount: 10 },
      { id: 'm4-p5', title: 'Stimulants & ADHD Meds', description: 'Methylphenidate, Adderall, Vyvanse, Atomoxetine, Guanfacine', drugIds: ['m4-25', 'm4-26', 'm4-27', 'm4-28', 'm4-29'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-5',
    title: 'Pain & Inflammation',
    subtitle: 'Analgesics, Opioids & Rheum',
    icon: 'Flame',
    color: Colors.chapterColors[4],
    parts: [
      { id: 'm5-p1', title: 'NSAIDs & Acetaminophen', description: 'Acetaminophen, Ibuprofen, Naproxen, Celecoxib, Meloxicam', drugIds: ['m5-1', 'm5-2', 'm5-3', 'm5-4', 'm5-5', 'm5-6', 'm5-7'], questionCount: 10 },
      { id: 'm5-p2', title: 'Opioids & Pain Management', description: 'Hydrocodone, Oxycodone, Morphine, Tramadol, Naloxone', drugIds: ['m5-8', 'm5-9', 'm5-10', 'm5-11', 'm5-12', 'm5-13', 'm5-14', 'm5-15'], questionCount: 12 },
      { id: 'm5-p3', title: 'Gout Medications', description: 'Allopurinol, Febuxostat, Colchicine', drugIds: ['m5-16', 'm5-17', 'm5-18'], questionCount: 8 },
      { id: 'm5-p4', title: 'DMARDs & Biologics', description: 'Methotrexate, Hydroxychloroquine, Adalimumab, Etanercept', drugIds: ['m5-19', 'm5-20', 'm5-21', 'm5-22', 'm5-23'], questionCount: 10 },
      { id: 'm5-p5', title: 'Systemic Steroids in Rheum', description: 'Methylprednisolone Acetate & steroid use in rheumatology', drugIds: ['m5-24', 'm3-25', 'm3-27'], questionCount: 8 },
    ],
  },
  {
    id: 'mod-6',
    title: 'Infectious Disease',
    subtitle: 'Antibiotics, Antifungals & Antivirals',
    icon: 'Bug',
    color: Colors.chapterColors[5],
    parts: [
      { id: 'm6-p1', title: 'Antibiotic Strategy & Big Buckets', description: 'Overview of spectrum, empiric therapy, resistance', drugIds: ['m6-1', 'm6-9', 'm6-16', 'm6-19'], questionCount: 8 },
      { id: 'm6-p2', title: 'Beta-Lactams (PCNs, Cephs)', description: 'Amoxicillin, Augmentin, Zosyn, Cephalexin, Ceftriaxone', drugIds: ['m6-1', 'm6-2', 'm6-3', 'm6-4', 'm6-5', 'm6-6', 'm6-7', 'm6-8'], questionCount: 12 },
      { id: 'm6-p3', title: 'Macrolides, FQs, Tetracyclines', description: 'Azithromycin, Ciprofloxacin, Levofloxacin, Doxycycline', drugIds: ['m6-9', 'm6-10', 'm6-11', 'm6-12', 'm6-13', 'm6-14', 'm6-15'], questionCount: 10 },
      { id: 'm6-p4', title: 'Sulfonamides & Others', description: 'TMP/SMX, Nitrofurantoin, Metronidazole, Vancomycin, Linezolid', drugIds: ['m6-16', 'm6-17', 'm6-18', 'm6-19', 'm6-20', 'm6-21'], questionCount: 10 },
      { id: 'm6-p5', title: 'Antifungals & Antivirals', description: 'Fluconazole, Nystatin, Acyclovir, Valacyclovir, Oseltamivir', drugIds: ['m6-22', 'm6-23', 'm6-24', 'm6-25', 'm6-26'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-7',
    title: 'Respiratory & Allergy',
    subtitle: 'Lungs, Airways & Antihistamines',
    icon: 'Wind',
    color: Colors.chapterColors[6],
    parts: [
      { id: 'm7-p1', title: 'Asthma/COPD Overview (Stepwise Logic)', description: 'Stepwise approach, controller vs. reliever', drugIds: ['m7-1', 'm7-3', 'm7-6', 'm7-10'], questionCount: 8 },
      { id: 'm7-p2', title: 'Inhaled Bronchodilators (SABA, LABA, LAMA)', description: 'Albuterol, Ipratropium, Tiotropium, Salmeterol, Formoterol', drugIds: ['m7-1', 'm7-2', 'm7-3', 'm7-4', 'm7-5'], questionCount: 10 },
      { id: 'm7-p3', title: 'Inhaled Corticosteroids & Combos', description: 'Fluticasone, Budesonide, Advair, Symbicort', drugIds: ['m7-6', 'm7-7', 'm7-8', 'm7-9'], questionCount: 8 },
      { id: 'm7-p4', title: 'Leukotriene Modifiers & Controllers', description: 'Montelukast, Theophylline', drugIds: ['m7-10', 'm7-11'], questionCount: 6 },
      { id: 'm7-p5', title: 'Antihistamines & Nasal Steroids', description: 'Cetirizine, Loratadine, Fexofenadine, Diphenhydramine, Flonase', drugIds: ['m7-12', 'm7-13', 'm7-14', 'm7-15', 'm7-16', 'm7-17'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-8',
    title: 'GI & Hepatic',
    subtitle: 'Digestive System & Liver',
    icon: 'Apple',
    color: Colors.chapterColors[7],
    parts: [
      { id: 'm8-p1', title: 'Acid Suppression (PPIs, H2 Blockers)', description: 'Omeprazole, Esomeprazole, Pantoprazole, Famotidine', drugIds: ['m8-1', 'm8-2', 'm8-3', 'm8-4', 'm8-5'], questionCount: 10 },
      { id: 'm8-p2', title: 'Antiemetics', description: 'Ondansetron, Metoclopramide, Promethazine, Scopolamine', drugIds: ['m8-6', 'm8-7', 'm8-8', 'm8-9', 'm8-10'], questionCount: 10 },
      { id: 'm8-p3', title: 'Laxatives & Antidiarrheals', description: 'Miralax, Docusate, Bisacodyl, Senna, Lactulose, Loperamide', drugIds: ['m8-11', 'm8-12', 'm8-13', 'm8-14', 'm8-15', 'm8-16'], questionCount: 10 },
      { id: 'm8-p4', title: 'Antispasmodics', description: 'Dicyclomine, Hyoscyamine', drugIds: ['m8-17', 'm8-18'], questionCount: 6 },
      { id: 'm8-p5', title: 'IBD & Liver-Related Drugs', description: 'Mesalamine, Infliximab, Rifaximin, Ursodiol', drugIds: ['m8-19', 'm8-20', 'm8-21', 'm8-22'], questionCount: 8 },
    ],
  },
  {
    id: 'mod-9',
    title: 'Neuro & Seizures',
    subtitle: 'Epilepsy, Migraine & Parkinson\'s',
    icon: 'Zap',
    color: Colors.chapterColors[8],
    parts: [
      { id: 'm9-p1', title: 'Seizure Meds Overview', description: 'Antiepileptic drug principles & monitoring', drugIds: ['m9-1', 'm9-4', 'm9-5'], questionCount: 8 },
      { id: 'm9-p2', title: 'Classic Antiepileptics', description: 'Phenytoin, Valproate, Carbamazepine', drugIds: ['m9-1', 'm9-2', 'm9-3'], questionCount: 8 },
      { id: 'm9-p3', title: 'Newer Antiepileptics', description: 'Levetiracetam, Lamotrigine, Topiramate, Gabapentin, Pregabalin', drugIds: ['m9-4', 'm9-5', 'm9-6', 'm9-7', 'm9-8', 'm9-9'], questionCount: 10 },
      { id: 'm9-p4', title: 'Migraine Acute & Preventive', description: 'Sumatriptan, Rizatriptan, Erenumab', drugIds: ['m9-10', 'm9-11', 'm9-12', 'm9-6', 'm1-18', 'm9-2'], questionCount: 10 },
      { id: 'm9-p5', title: 'Parkinson\'s Disease Medications', description: 'Carbidopa/Levodopa, Pramipexole, Ropinirole, Rasagiline', drugIds: ['m9-13', 'm9-14', 'm9-15', 'm9-16', 'm9-17', 'm9-18'], questionCount: 10 },
    ],
  },
  {
    id: 'mod-10',
    title: 'GU & Miscellaneous',
    subtitle: 'End-Organs & High-Yield Drugs',
    icon: 'Shield',
    color: Colors.chapterColors[9],
    parts: [
      { id: 'm10-p1', title: 'BPH & Overactive Bladder', description: 'Tamsulosin, Finasteride, Oxybutynin, Mirabegron', drugIds: ['m10-1', 'm10-2', 'm10-3', 'm10-4', 'm10-5', 'm10-6', 'm10-7', 'm10-8'], questionCount: 10 },
      { id: 'm10-p2', title: 'Osteoporosis & Bone Health', description: 'Alendronate, Zoledronic Acid, Denosumab, Raloxifene', drugIds: ['m10-9', 'm10-10', 'm10-11', 'm10-12', 'm10-13'], questionCount: 10 },
      { id: 'm10-p3', title: 'Contraceptives & Hormonal Therapy', description: 'COCs, Medroxyprogesterone, Estradiol, Conjugated Estrogens', drugIds: ['m10-14', 'm10-15', 'm10-16', 'm10-17'], questionCount: 8 },
      { id: 'm10-p4', title: 'Smoking Cessation & Dependence', description: 'Varenicline, Nicotine Replacement Therapy', drugIds: ['m10-18', 'm10-19', 'm10-10'], questionCount: 6 },
      { id: 'm10-p5', title: 'Eye/Ear & Misc Top 300 Drugs', description: 'Latanoprost, Timolol, Ciprodex, Sevelamer, Epoetin Alfa', drugIds: ['m10-20', 'm10-21', 'm10-22', 'm10-23', 'm10-24', 'm10-25'], questionCount: 10 },
    ],
  },
];

export function getChapterById(id: string): Chapter | undefined {
  return chapters.find(c => c.id === id);
}
