import { Drug } from './types';

export const drugs: Drug[] = [
  // MODULE 1 – Cardiovascular I: HTN & HF
  // 1b: ACE Inhibitors & ARBs
  { id: 'm1-1', brandName: 'Prinivil/Zestril', genericName: 'Lisinopril', drugClass: 'ACE Inhibitor', indications: ['Hypertension', 'Heart failure', 'Post-MI'], commonDosing: '5-40 mg PO daily', sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema'], keyFact: 'ACE inhibitors cause dry cough in ~10% of patients' },
  { id: 'm1-2', brandName: 'Vasotec', genericName: 'Enalapril', drugClass: 'ACE Inhibitor', indications: ['Hypertension', 'Heart failure'], commonDosing: '2.5-40 mg PO daily (divided BID)', sideEffects: ['Dry cough', 'Hyperkalemia', 'Hypotension'], keyFact: 'Prodrug converted to enalaprilat; available IV as enalaprilat' },
  { id: 'm1-3', brandName: 'Altace', genericName: 'Ramipril', drugClass: 'ACE Inhibitor', indications: ['Hypertension', 'Heart failure', 'CV risk reduction'], commonDosing: '2.5-20 mg PO daily', sideEffects: ['Dry cough', 'Hyperkalemia', 'Dizziness'], keyFact: 'HOPE trial showed CV risk reduction in high-risk patients' },
  { id: 'm1-4', brandName: 'Cozaar', genericName: 'Losartan', drugClass: 'Angiotensin II Receptor Blocker (ARB)', indications: ['Hypertension', 'Diabetic nephropathy', 'Stroke prevention'], commonDosing: '25-100 mg PO daily', sideEffects: ['Hyperkalemia', 'Dizziness', 'Hypotension'], keyFact: 'Also has uricosuric effect (lowers uric acid)' },
  { id: 'm1-5', brandName: 'Diovan', genericName: 'Valsartan', drugClass: 'Angiotensin II Receptor Blocker (ARB)', indications: ['Hypertension', 'Heart failure', 'Post-MI'], commonDosing: '80-320 mg PO daily', sideEffects: ['Hyperkalemia', 'Dizziness', 'Hypotension'], keyFact: 'ARBs are alternatives for patients with ACE inhibitor cough' },
  { id: 'm1-6', brandName: 'Avapro', genericName: 'Irbesartan', drugClass: 'Angiotensin II Receptor Blocker (ARB)', indications: ['Hypertension', 'Diabetic nephropathy'], commonDosing: '150-300 mg PO daily', sideEffects: ['Dizziness', 'Hyperkalemia', 'Fatigue'], keyFact: 'Proven nephroprotection in type 2 diabetic nephropathy' },
  { id: 'm1-7', brandName: 'Lotensin', genericName: 'Benazepril', drugClass: 'ACE Inhibitor', indications: ['Hypertension'], commonDosing: '10-40 mg PO daily', sideEffects: ['Dry cough', 'Hyperkalemia', 'Headache'], keyFact: 'Prodrug; hepatically converted to active benazeprilat' },

  // 1c: Thiazide & Loop Diuretics
  { id: 'm1-8', brandName: 'Hydrochlorothiazide', genericName: 'Hydrochlorothiazide (HCTZ)', drugClass: 'Thiazide Diuretic', indications: ['Hypertension', 'Edema'], commonDosing: '12.5-50 mg PO daily', sideEffects: ['Hypokalemia', 'Hyperuricemia', 'Photosensitivity'], keyFact: 'First-line for HTN; causes electrolyte imbalances' },
  { id: 'm1-9', brandName: 'Thalitone', genericName: 'Chlorthalidone', drugClass: 'Thiazide-like Diuretic', indications: ['Hypertension', 'Edema'], commonDosing: '12.5-25 mg PO daily', sideEffects: ['Hypokalemia', 'Hyponatremia', 'Hyperuricemia'], keyFact: 'Longer half-life than HCTZ; preferred in guidelines for HTN' },
  { id: 'm1-10', brandName: 'Lasix', genericName: 'Furosemide', drugClass: 'Loop Diuretic', indications: ['Edema', 'Heart failure', 'Pulmonary edema'], commonDosing: '20-80 mg PO/IV daily-BID', sideEffects: ['Hypokalemia', 'Ototoxicity', 'Dehydration'], keyFact: 'Most commonly used loop diuretic; oral bioavailability ~50%' },
  { id: 'm1-11', brandName: 'Bumex', genericName: 'Bumetanide', drugClass: 'Loop Diuretic', indications: ['Edema', 'Heart failure'], commonDosing: '0.5-2 mg PO/IV daily-BID', sideEffects: ['Hypokalemia', 'Ototoxicity', 'Dehydration'], keyFact: '40:1 potency ratio (furosemide 40 mg ≈ bumetanide 1 mg)' },
  { id: 'm1-12', brandName: 'Demadex', genericName: 'Torsemide', drugClass: 'Loop Diuretic', indications: ['Edema', 'Heart failure'], commonDosing: '10-20 mg PO/IV daily', sideEffects: ['Hypokalemia', 'Dizziness', 'Headache'], keyFact: 'Better oral bioavailability (~80%) than furosemide' },
  { id: 'm1-13', brandName: 'Microzide', genericName: 'Indapamide', drugClass: 'Thiazide-like Diuretic', indications: ['Hypertension', 'Edema'], commonDosing: '1.25-2.5 mg PO daily', sideEffects: ['Hypokalemia', 'Hyponatremia', 'Dizziness'], keyFact: 'Thiazide-like but also has vasodilatory properties' },

  // 1d: Beta-Blockers
  { id: 'm1-14', brandName: 'Lopressor', genericName: 'Metoprolol Tartrate', drugClass: 'Beta-1 Selective Blocker', indications: ['Hypertension', 'Angina', 'MI'], commonDosing: '25-100 mg PO BID', sideEffects: ['Bradycardia', 'Fatigue', 'Hypotension'], keyFact: 'Tartrate is immediate-release, given BID' },
  { id: 'm1-15', brandName: 'Toprol-XL', genericName: 'Metoprolol Succinate', drugClass: 'Beta-1 Selective Blocker', indications: ['Hypertension', 'Heart failure', 'Angina'], commonDosing: '25-200 mg PO daily', sideEffects: ['Bradycardia', 'Fatigue', 'Dizziness'], keyFact: 'Succinate is extended-release; proven mortality benefit in HFrEF' },
  { id: 'm1-16', brandName: 'Coreg', genericName: 'Carvedilol', drugClass: 'Non-selective Beta/Alpha-1 Blocker', indications: ['Heart failure', 'Hypertension', 'Post-MI LV dysfunction'], commonDosing: '3.125-25 mg PO BID', sideEffects: ['Dizziness', 'Hypotension', 'Weight gain'], keyFact: 'Alpha + Beta blockade; must take with food' },
  { id: 'm1-17', brandName: 'Tenormin', genericName: 'Atenolol', drugClass: 'Beta-1 Selective Blocker', indications: ['Hypertension', 'Angina'], commonDosing: '25-100 mg PO daily', sideEffects: ['Bradycardia', 'Fatigue', 'Cold extremities'], keyFact: 'Renally eliminated; dose adjust in renal impairment' },
  { id: 'm1-18', brandName: 'Inderal', genericName: 'Propranolol', drugClass: 'Non-selective Beta Blocker', indications: ['Hypertension', 'Migraine prophylaxis', 'Essential tremor', 'Performance anxiety'], commonDosing: '20-80 mg PO BID-TID (IR)', sideEffects: ['Bradycardia', 'Bronchospasm', 'Fatigue'], keyFact: 'Non-selective; avoid in asthma/COPD; lipophilic (crosses BBB)' },
  { id: 'm1-19', brandName: 'Zebeta', genericName: 'Bisoprolol', drugClass: 'Beta-1 Selective Blocker', indications: ['Hypertension', 'Heart failure'], commonDosing: '2.5-10 mg PO daily', sideEffects: ['Bradycardia', 'Fatigue', 'Dizziness'], keyFact: 'One of three beta-blockers proven to reduce mortality in HFrEF' },
  { id: 'm1-20', brandName: 'Bystolic', genericName: 'Nebivolol', drugClass: 'Beta-1 Selective Blocker', indications: ['Hypertension'], commonDosing: '5-40 mg PO daily', sideEffects: ['Headache', 'Fatigue', 'Dizziness'], keyFact: 'Also causes NO-mediated vasodilation' },

  // 1e: MRAs & ARNI
  { id: 'm1-21', brandName: 'Aldactone', genericName: 'Spironolactone', drugClass: 'Potassium-Sparing Diuretic (MRA)', indications: ['Heart failure', 'Ascites', 'Hypertension', 'Primary aldosteronism'], commonDosing: '12.5-50 mg PO daily', sideEffects: ['Hyperkalemia', 'Gynecomastia', 'GI upset'], keyFact: 'MRA that reduces mortality in HFrEF (RALES trial)' },
  { id: 'm1-22', brandName: 'Inspra', genericName: 'Eplerenone', drugClass: 'Potassium-Sparing Diuretic (MRA)', indications: ['Heart failure post-MI', 'Hypertension'], commonDosing: '25-50 mg PO daily', sideEffects: ['Hyperkalemia', 'Dizziness', 'Diarrhea'], keyFact: 'More selective MRA than spironolactone; less gynecomastia' },
  { id: 'm1-23', brandName: 'Entresto', genericName: 'Sacubitril/Valsartan', drugClass: 'ARNI (Neprilysin Inhibitor + ARB)', indications: ['Heart failure with reduced EF'], commonDosing: '24/26 mg to 97/103 mg PO BID', sideEffects: ['Hypotension', 'Hyperkalemia', 'Angioedema'], keyFact: 'Must washout ACEi 36 hrs before starting; PARADIGM-HF trial' },

  // 1f: Putting It Together (uses drugs from 1b-1e, plus extras)
  { id: 'm1-24', brandName: 'Apresoline', genericName: 'Hydralazine', drugClass: 'Direct Vasodilator', indications: ['Hypertension', 'Heart failure (with isosorbide dinitrate)'], commonDosing: '25-100 mg PO TID', sideEffects: ['Reflex tachycardia', 'Headache', 'Drug-induced lupus'], keyFact: 'BiDil (hydralazine + ISDN) shown to benefit African American HF patients' },
  { id: 'm1-25', brandName: 'Catapres', genericName: 'Clonidine', drugClass: 'Central Alpha-2 Agonist', indications: ['Hypertension', 'ADHD', 'Opioid withdrawal'], commonDosing: '0.1-0.3 mg PO BID or patch weekly', sideEffects: ['Drowsiness', 'Dry mouth', 'Rebound hypertension'], keyFact: 'Never abruptly discontinue; rebound HTN crisis risk' },

  // MODULE 2 – Cardiovascular II: Lipids & Thrombosis
  // 2a: Statins
  { id: 'm2-1', brandName: 'Lipitor', genericName: 'Atorvastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia', 'ASCVD prevention'], commonDosing: '10-80 mg PO daily', sideEffects: ['Myalgia', 'Hepatotoxicity', 'Rhabdomyolysis'], keyFact: 'High-intensity statin at 40-80 mg; can be given any time of day' },
  { id: 'm2-2', brandName: 'Crestor', genericName: 'Rosuvastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia', 'ASCVD prevention'], commonDosing: '5-40 mg PO daily', sideEffects: ['Myalgia', 'Headache', 'Proteinuria'], keyFact: 'High-intensity at 20-40 mg; longest half-life among statins' },
  { id: 'm2-3', brandName: 'Zocor', genericName: 'Simvastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia', 'CHD risk reduction'], commonDosing: '10-40 mg PO daily at bedtime', sideEffects: ['Myalgia', 'GI upset', 'Elevated LFTs'], keyFact: '80 mg dose restricted due to myopathy risk; take at bedtime' },
  { id: 'm2-4', brandName: 'Pravachol', genericName: 'Pravastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia', 'CV prevention'], commonDosing: '10-80 mg PO daily', sideEffects: ['Myalgia', 'GI upset', 'Headache'], keyFact: 'Not metabolized by CYP3A4; fewer drug interactions' },
  { id: 'm2-5', brandName: 'Lescol', genericName: 'Fluvastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia'], commonDosing: '20-80 mg PO daily', sideEffects: ['Myalgia', 'GI upset', 'Headache'], keyFact: 'Low-intensity statin; CYP2C9 metabolism' },
  { id: 'm2-6', brandName: 'Livalo', genericName: 'Pitavastatin', drugClass: 'HMG-CoA Reductase Inhibitor (Statin)', indications: ['Hyperlipidemia'], commonDosing: '1-4 mg PO daily', sideEffects: ['Myalgia', 'Constipation', 'Back pain'], keyFact: 'Minimal CYP metabolism; may increase HDL more than other statins' },

  // 2b: Non-statin Lipid Agents
  { id: 'm2-7', brandName: 'Zetia', genericName: 'Ezetimibe', drugClass: 'Cholesterol Absorption Inhibitor', indications: ['Hyperlipidemia (adjunct to statin)'], commonDosing: '10 mg PO daily', sideEffects: ['Diarrhea', 'Arthralgia', 'Fatigue'], keyFact: 'Blocks intestinal cholesterol absorption; often combined with statin' },
  { id: 'm2-8', brandName: 'Tricor', genericName: 'Fenofibrate', drugClass: 'Fibrate (PPARα agonist)', indications: ['Hypertriglyceridemia', 'Mixed dyslipidemia'], commonDosing: '48-145 mg PO daily', sideEffects: ['GI upset', 'Myopathy (esp. with statin)', 'Cholelithiasis'], keyFact: 'Primarily lowers triglycerides; increases myopathy risk with statins' },
  { id: 'm2-9', brandName: 'Repatha', genericName: 'Evolocumab', drugClass: 'PCSK9 Inhibitor', indications: ['Familial hypercholesterolemia', 'ASCVD (statin adjunct)'], commonDosing: '140 mg SC every 2 weeks or 420 mg SC monthly', sideEffects: ['Injection site reactions', 'Nasopharyngitis', 'Myalgia'], keyFact: 'Monoclonal antibody; potent LDL reduction up to 60%' },
  { id: 'm2-10', brandName: 'Niaspan', genericName: 'Niacin (Vitamin B3)', drugClass: 'Nicotinic Acid', indications: ['Dyslipidemia'], commonDosing: '500-2000 mg PO daily at bedtime', sideEffects: ['Flushing', 'Hepatotoxicity', 'Hyperglycemia'], keyFact: 'Take aspirin 30 min before to reduce flushing; raises HDL' },
  { id: 'm2-11', brandName: 'Vascepa', genericName: 'Icosapent Ethyl', drugClass: 'Omega-3 Fatty Acid (EPA)', indications: ['Hypertriglyceridemia', 'CV risk reduction'], commonDosing: '2 g PO BID with food', sideEffects: ['Arthralgia', 'Atrial fibrillation', 'Bleeding'], keyFact: 'REDUCE-IT trial showed 25% CV risk reduction' },

  // 2c: Antiplatelets
  { id: 'm2-12', brandName: 'Aspirin', genericName: 'Aspirin', drugClass: 'Irreversible COX Inhibitor/Antiplatelet', indications: ['ACS', 'Stroke prevention', 'Pain', 'Fever'], commonDosing: '81 mg daily (cardioprotection); 325-650 mg q4-6h (pain)', sideEffects: ['GI bleeding', 'Tinnitus', 'Reye syndrome (children)'], keyFact: 'Low-dose for antiplatelet; irreversibly inhibits COX for platelet lifespan' },
  { id: 'm2-13', brandName: 'Plavix', genericName: 'Clopidogrel', drugClass: 'P2Y12 Platelet Inhibitor', indications: ['ACS', 'Stroke prevention', 'PAD'], commonDosing: '75 mg PO daily (300-600 mg loading)', sideEffects: ['Bleeding', 'Bruising', 'TTP (rare)'], keyFact: 'Prodrug activated by CYP2C19; genetic testing may guide therapy' },
  { id: 'm2-14', brandName: 'Brilinta', genericName: 'Ticagrelor', drugClass: 'P2Y12 Platelet Inhibitor', indications: ['ACS'], commonDosing: '90 mg PO BID (180 mg loading)', sideEffects: ['Bleeding', 'Dyspnea', 'Bradycardia'], keyFact: 'Reversible P2Y12 inhibitor; must take with aspirin ≤100 mg' },
  { id: 'm2-15', brandName: 'Effient', genericName: 'Prasugrel', drugClass: 'P2Y12 Platelet Inhibitor', indications: ['ACS (with PCI)'], commonDosing: '10 mg PO daily (60 mg loading)', sideEffects: ['Bleeding', 'Bruising', 'Rash'], keyFact: 'Contraindicated in prior stroke/TIA and age ≥75' },

  // 2d: Anticoagulants
  { id: 'm2-16', brandName: 'Coumadin', genericName: 'Warfarin', drugClass: 'Vitamin K Antagonist', indications: ['Atrial fibrillation', 'DVT/PE', 'Mechanical heart valves'], commonDosing: 'Variable; titrate to INR 2-3', sideEffects: ['Bleeding', 'Skin necrosis', 'Purple toe syndrome'], keyFact: 'Many drug & food interactions; CYP2C9/VKORC1 genetics affect dosing' },
  { id: 'm2-17', brandName: 'Eliquis', genericName: 'Apixaban', drugClass: 'Factor Xa Inhibitor (DOAC)', indications: ['Atrial fibrillation', 'DVT/PE treatment & prophylaxis'], commonDosing: '5 mg PO BID (AFib); 10 mg BID x7d then 5 mg BID (DVT/PE)', sideEffects: ['Bleeding', 'Bruising', 'Anemia'], keyFact: 'No routine monitoring; reversible with andexanet alfa (Andexxa)' },
  { id: 'm2-18', brandName: 'Xarelto', genericName: 'Rivaroxaban', drugClass: 'Factor Xa Inhibitor (DOAC)', indications: ['Atrial fibrillation', 'DVT/PE', 'VTE prophylaxis'], commonDosing: '20 mg PO daily with evening meal (AFib)', sideEffects: ['Bleeding', 'GI bleeding', 'Anemia'], keyFact: 'Must take with food for adequate absorption at ≥15 mg doses' },
  { id: 'm2-19', brandName: 'Pradaxa', genericName: 'Dabigatran', drugClass: 'Direct Thrombin Inhibitor (DOAC)', indications: ['Atrial fibrillation', 'DVT/PE'], commonDosing: '150 mg PO BID', sideEffects: ['Bleeding', 'Dyspepsia', 'GI bleeding'], keyFact: 'Reversible with idarucizumab (Praxbind); renally eliminated' },
  { id: 'm2-20', brandName: 'Lovenox', genericName: 'Enoxaparin', drugClass: 'Low Molecular Weight Heparin', indications: ['DVT/PE treatment & prophylaxis', 'ACS'], commonDosing: '1 mg/kg SC BID (treatment); 40 mg SC daily (prophylaxis)', sideEffects: ['Bleeding', 'HIT', 'Injection site bruising'], keyFact: 'Monitor anti-Xa levels in obesity & renal impairment' },
  { id: 'm2-21', brandName: 'Heparin', genericName: 'Heparin (Unfractionated)', drugClass: 'Unfractionated Heparin', indications: ['DVT/PE', 'ACS', 'Anticoagulation during procedures'], commonDosing: 'Weight-based IV protocol; 5000 units SC q8-12h (prophylaxis)', sideEffects: ['Bleeding', 'HIT', 'Osteoporosis (long-term)'], keyFact: 'Monitor aPTT; reversible with protamine sulfate' },

  // 2e: Antianginals & Nitrates
  { id: 'm2-22', brandName: 'Nitrostat', genericName: 'Nitroglycerin', drugClass: 'Nitrate (Vasodilator)', indications: ['Acute angina', 'Angina prophylaxis'], commonDosing: '0.4 mg SL q5min x3 PRN; patch 0.2-0.8 mg/hr', sideEffects: ['Headache', 'Hypotension', 'Reflex tachycardia'], keyFact: 'Must have 10-12 hr nitrate-free interval to prevent tolerance' },
  { id: 'm2-23', brandName: 'Imdur', genericName: 'Isosorbide Mononitrate', drugClass: 'Nitrate (Vasodilator)', indications: ['Angina prophylaxis'], commonDosing: '30-120 mg PO daily (ER)', sideEffects: ['Headache', 'Dizziness', 'Hypotension'], keyFact: 'Active metabolite of isosorbide dinitrate; daily dosing for ER' },
  { id: 'm2-24', brandName: 'Norvasc', genericName: 'Amlodipine', drugClass: 'Calcium Channel Blocker (DHP)', indications: ['Hypertension', 'Angina'], commonDosing: '2.5-10 mg PO daily', sideEffects: ['Peripheral edema', 'Dizziness', 'Flushing'], keyFact: 'Long-acting DHP CCB; no significant heart rate effects' },
  { id: 'm2-25', brandName: 'Cardizem', genericName: 'Diltiazem', drugClass: 'Calcium Channel Blocker (Non-DHP)', indications: ['Hypertension', 'Angina', 'Atrial fibrillation/flutter'], commonDosing: '120-360 mg PO daily (ER)', sideEffects: ['Bradycardia', 'Constipation', 'Edema'], keyFact: 'Non-DHP CCB; slows heart rate; avoid with beta-blockers' },
  { id: 'm2-26', brandName: 'Ranexa', genericName: 'Ranolazine', drugClass: 'Late Sodium Current Inhibitor', indications: ['Chronic angina'], commonDosing: '500-1000 mg PO BID', sideEffects: ['Dizziness', 'Nausea', 'Constipation', 'QT prolongation'], keyFact: 'Does not affect heart rate or BP; add-on for refractory angina' },

  // MODULE 3 – Endocrine & Diabetes
  // 3a: Insulins
  { id: 'm3-1', brandName: 'Lantus', genericName: 'Insulin Glargine', drugClass: 'Long-acting Insulin (Basal)', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: '10-80+ units SC daily', sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy'], keyFact: 'Peakless ~24-hour basal insulin; do not mix with other insulins' },
  { id: 'm3-2', brandName: 'Levemir', genericName: 'Insulin Detemir', drugClass: 'Long-acting Insulin (Basal)', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: '10-60+ units SC daily or BID', sideEffects: ['Hypoglycemia', 'Weight gain', 'Injection site reactions'], keyFact: 'Albumin-bound; may need BID dosing; less weight gain than glargine' },
  { id: 'm3-3', brandName: 'Tresiba', genericName: 'Insulin Degludec', drugClass: 'Ultra-long-acting Insulin (Basal)', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: '10-80+ units SC daily', sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy'], keyFact: 'Duration >42 hours; flexible dosing timing; less hypoglycemia' },
  { id: 'm3-4', brandName: 'Humalog', genericName: 'Insulin Lispro', drugClass: 'Rapid-acting Insulin (Bolus)', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: 'Variable; given 0-15 min before meals', sideEffects: ['Hypoglycemia', 'Weight gain', 'Injection site reactions'], keyFact: 'Onset 15 min, peak 1-2 hr, duration 3-5 hr' },
  { id: 'm3-5', brandName: 'NovoLog', genericName: 'Insulin Aspart', drugClass: 'Rapid-acting Insulin (Bolus)', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: 'Variable; given 0-15 min before meals', sideEffects: ['Hypoglycemia', 'Weight gain', 'Hypokalemia'], keyFact: 'Similar to lispro; can be used in insulin pumps' },
  { id: 'm3-6', brandName: 'Humulin N', genericName: 'NPH Insulin', drugClass: 'Intermediate-acting Insulin', indications: ['Type 1 & Type 2 Diabetes'], commonDosing: 'Variable; SC BID', sideEffects: ['Hypoglycemia', 'Weight gain', 'Injection site reactions'], keyFact: 'Cloudy suspension; must mix gently; peak at 4-12 hr' },
  { id: 'm3-7', brandName: 'Humulin R', genericName: 'Regular Insulin', drugClass: 'Short-acting Insulin', indications: ['Type 1 & Type 2 Diabetes', 'Hyperkalemia', 'DKA'], commonDosing: 'Variable; SC 30 min before meals or IV', sideEffects: ['Hypoglycemia', 'Weight gain', 'Hypokalemia'], keyFact: 'Only insulin that can be given IV; onset 30-60 min SC' },

  // 3b: Metformin & Oral Agents
  { id: 'm3-8', brandName: 'Glucophage', genericName: 'Metformin', drugClass: 'Biguanide', indications: ['Type 2 Diabetes'], commonDosing: '500-1000 mg PO BID (with meals)', sideEffects: ['GI upset', 'Lactic acidosis (rare)', 'B12 deficiency'], keyFact: 'First-line for T2DM; hold 48 hr around iodinated contrast' },
  { id: 'm3-9', brandName: 'Actos', genericName: 'Pioglitazone', drugClass: 'Thiazolidinedione (TZD)', indications: ['Type 2 Diabetes'], commonDosing: '15-45 mg PO daily', sideEffects: ['Weight gain', 'Edema', 'Fracture risk', 'Bladder cancer concern'], keyFact: 'PPARγ agonist; avoid in NYHA III/IV heart failure' },

  // 3c: SGLT2 Inhibitors
  { id: 'm3-10', brandName: 'Jardiance', genericName: 'Empagliflozin', drugClass: 'SGLT2 Inhibitor', indications: ['Type 2 Diabetes', 'Heart failure', 'CKD'], commonDosing: '10-25 mg PO daily', sideEffects: ['UTI', 'Genital yeast infections', 'DKA (euglycemic)'], keyFact: 'EMPA-REG showed CV mortality benefit; causes glucosuria' },
  { id: 'm3-11', brandName: 'Farxiga', genericName: 'Dapagliflozin', drugClass: 'SGLT2 Inhibitor', indications: ['Type 2 Diabetes', 'Heart failure', 'CKD'], commonDosing: '5-10 mg PO daily', sideEffects: ['UTI', 'Genital infections', 'Volume depletion'], keyFact: 'DAPA-HF/DAPA-CKD: benefits in HF & CKD regardless of diabetes' },
  { id: 'm3-12', brandName: 'Invokana', genericName: 'Canagliflozin', drugClass: 'SGLT2 Inhibitor', indications: ['Type 2 Diabetes', 'Diabetic nephropathy'], commonDosing: '100-300 mg PO daily before breakfast', sideEffects: ['UTI', 'Genital infections', 'Amputation risk', 'Fracture risk'], keyFact: 'First SGLT2i approved; CREDENCE trial showed renal benefit' },

  // 3d: GLP-1, DPP-4, Sulfonylureas
  { id: 'm3-13', brandName: 'Ozempic', genericName: 'Semaglutide (injectable)', drugClass: 'GLP-1 Receptor Agonist', indications: ['Type 2 Diabetes', 'CV risk reduction'], commonDosing: '0.25 mg SC weekly, titrate to 1-2 mg weekly', sideEffects: ['Nausea', 'Vomiting', 'Pancreatitis risk'], keyFact: 'Weekly injection; also promotes significant weight loss' },
  { id: 'm3-14', brandName: 'Rybelsus', genericName: 'Semaglutide (oral)', drugClass: 'GLP-1 Receptor Agonist', indications: ['Type 2 Diabetes'], commonDosing: '3 mg PO daily, titrate to 7-14 mg daily', sideEffects: ['Nausea', 'Diarrhea', 'Decreased appetite'], keyFact: 'First oral GLP-1 RA; take on empty stomach with ≤4 oz water' },
  { id: 'm3-15', brandName: 'Trulicity', genericName: 'Dulaglutide', drugClass: 'GLP-1 Receptor Agonist', indications: ['Type 2 Diabetes'], commonDosing: '0.75-4.5 mg SC weekly', sideEffects: ['Nausea', 'Diarrhea', 'Injection site reactions'], keyFact: 'Weekly GLP-1 RA; CV benefit demonstrated in REWIND trial' },
  { id: 'm3-16', brandName: 'Victoza', genericName: 'Liraglutide', drugClass: 'GLP-1 Receptor Agonist', indications: ['Type 2 Diabetes', 'CV risk reduction'], commonDosing: '0.6-1.8 mg SC daily', sideEffects: ['Nausea', 'Vomiting', 'Pancreatitis risk'], keyFact: 'Daily injection; LEADER trial showed CV benefit' },
  { id: 'm3-17', brandName: 'Januvia', genericName: 'Sitagliptin', drugClass: 'DPP-4 Inhibitor', indications: ['Type 2 Diabetes'], commonDosing: '100 mg PO daily', sideEffects: ['Nasopharyngitis', 'Headache', 'Joint pain'], keyFact: 'Weight neutral; dose adjust in renal impairment' },
  { id: 'm3-18', brandName: 'Tradjenta', genericName: 'Linagliptin', drugClass: 'DPP-4 Inhibitor', indications: ['Type 2 Diabetes'], commonDosing: '5 mg PO daily', sideEffects: ['Nasopharyngitis', 'Headache', 'Hypoglycemia (with SU)'], keyFact: 'No renal dose adjustment needed; biliary excretion' },
  { id: 'm3-19', brandName: 'Glucotrol', genericName: 'Glipizide', drugClass: 'Sulfonylurea (2nd generation)', indications: ['Type 2 Diabetes'], commonDosing: '5-20 mg PO daily (before meals)', sideEffects: ['Hypoglycemia', 'Weight gain', 'GI upset'], keyFact: 'Shorter-acting SU; take 30 min before meals' },
  { id: 'm3-20', brandName: 'Amaryl', genericName: 'Glimepiride', drugClass: 'Sulfonylurea (2nd generation)', indications: ['Type 2 Diabetes'], commonDosing: '1-8 mg PO daily', sideEffects: ['Hypoglycemia', 'Weight gain', 'Dizziness'], keyFact: 'Once daily dosing; lower hypoglycemia risk than glyburide' },
  { id: 'm3-21', brandName: 'DiaBeta', genericName: 'Glyburide', drugClass: 'Sulfonylurea (2nd generation)', indications: ['Type 2 Diabetes'], commonDosing: '2.5-20 mg PO daily', sideEffects: ['Hypoglycemia', 'Weight gain', 'GI upset'], keyFact: 'Highest hypoglycemia risk among SUs; avoid in elderly & CKD' },

  // 3e: Thyroid
  { id: 'm3-22', brandName: 'Synthroid', genericName: 'Levothyroxine', drugClass: 'Thyroid Hormone (T4)', indications: ['Hypothyroidism', 'TSH suppression in thyroid cancer'], commonDosing: '1.6 mcg/kg/day PO; take on empty stomach', sideEffects: ['Tachycardia', 'Weight loss', 'Insomnia'], keyFact: 'Take 30-60 min before breakfast; separate from calcium, iron, PPIs' },
  { id: 'm3-23', brandName: 'Tapazole', genericName: 'Methimazole', drugClass: 'Antithyroid Agent', indications: ['Hyperthyroidism', 'Graves disease'], commonDosing: '5-30 mg PO daily', sideEffects: ['Agranulocytosis', 'Rash', 'Hepatotoxicity'], keyFact: 'Preferred over PTU except in 1st trimester pregnancy' },
  { id: 'm3-24', brandName: 'PTU', genericName: 'Propylthiouracil', drugClass: 'Antithyroid Agent', indications: ['Hyperthyroidism', 'Thyroid storm'], commonDosing: '100-150 mg PO TID', sideEffects: ['Agranulocytosis', 'Hepatotoxicity (black box)', 'Rash'], keyFact: 'Preferred in 1st trimester; also blocks T4→T3 conversion' },

  // 3f: Adrenal Steroids
  { id: 'm3-25', brandName: 'Prednisone', genericName: 'Prednisone', drugClass: 'Systemic Corticosteroid', indications: ['Inflammation', 'Autoimmune disorders', 'Asthma exacerbation'], commonDosing: '5-60 mg PO daily; taper for prolonged use', sideEffects: ['Hyperglycemia', 'Osteoporosis', 'Adrenal suppression'], keyFact: 'Taper if >2 weeks use; immunosuppressive at high doses' },
  { id: 'm3-26', brandName: 'Orapred', genericName: 'Prednisolone', drugClass: 'Systemic Corticosteroid', indications: ['Inflammation', 'Asthma', 'Autoimmune conditions'], commonDosing: '5-60 mg PO daily', sideEffects: ['Hyperglycemia', 'Insomnia', 'GI upset'], keyFact: 'Active form of prednisone; preferred in hepatic impairment' },
  { id: 'm3-27', brandName: 'Medrol', genericName: 'Methylprednisolone', drugClass: 'Systemic Corticosteroid', indications: ['Inflammation', 'MS exacerbation', 'Transplant rejection'], commonDosing: '4-48 mg PO daily; 125-1000 mg IV (pulse)', sideEffects: ['Hyperglycemia', 'Insomnia', 'GI upset'], keyFact: 'Available as Medrol Dosepak (tapered 6-day course)' },
  { id: 'm3-28', brandName: 'Decadron', genericName: 'Dexamethasone', drugClass: 'Systemic Corticosteroid', indications: ['Cerebral edema', 'Chemo-induced N/V', 'COVID-19', 'Croup'], commonDosing: '0.5-10 mg PO/IV daily', sideEffects: ['Hyperglycemia', 'Insomnia', 'Immunosuppression'], keyFact: 'Most potent oral steroid (25x potency of hydrocortisone); long-acting' },
  { id: 'm3-29', brandName: 'Cortef', genericName: 'Hydrocortisone', drugClass: 'Systemic Corticosteroid', indications: ['Adrenal insufficiency', 'Inflammation'], commonDosing: '15-25 mg PO daily (divided); 100 mg IV (stress dosing)', sideEffects: ['Hyperglycemia', 'Fluid retention', 'Adrenal suppression'], keyFact: 'Most physiologic steroid for adrenal replacement; short-acting' },

  // MODULE 4 – CNS & Psych
  // 4a: SSRIs, SNRIs
  { id: 'm4-1', brandName: 'Zoloft', genericName: 'Sertraline', drugClass: 'SSRI', indications: ['Depression', 'Anxiety', 'PTSD', 'OCD'], commonDosing: '50-200 mg PO daily', sideEffects: ['GI upset', 'Sexual dysfunction', 'Insomnia'], keyFact: 'Most serotonin-selective SSRI; first-line for many conditions' },
  { id: 'm4-2', brandName: 'Lexapro', genericName: 'Escitalopram', drugClass: 'SSRI', indications: ['Depression', 'Generalized anxiety disorder'], commonDosing: '10-20 mg PO daily', sideEffects: ['Nausea', 'Sexual dysfunction', 'QT prolongation at high doses'], keyFact: 'S-enantiomer of citalopram; max 20 mg/day' },
  { id: 'm4-3', brandName: 'Prozac', genericName: 'Fluoxetine', drugClass: 'SSRI', indications: ['Depression', 'OCD', 'Bulimia', 'Panic disorder'], commonDosing: '20-80 mg PO daily', sideEffects: ['Insomnia', 'GI upset', 'Activation'], keyFact: 'Longest half-life SSRI (~7-9 day active metabolite); CYP2D6 inhibitor' },
  { id: 'm4-4', brandName: 'Paxil', genericName: 'Paroxetine', drugClass: 'SSRI', indications: ['Depression', 'GAD', 'Social anxiety', 'PTSD'], commonDosing: '20-50 mg PO daily', sideEffects: ['Sedation', 'Weight gain', 'Sexual dysfunction', 'Discontinuation syndrome'], keyFact: 'Most anticholinergic SSRI; hardest to discontinue; avoid in pregnancy' },
  { id: 'm4-5', brandName: 'Celexa', genericName: 'Citalopram', drugClass: 'SSRI', indications: ['Depression'], commonDosing: '20-40 mg PO daily', sideEffects: ['Nausea', 'Sexual dysfunction', 'QT prolongation'], keyFact: 'Max 20 mg/day in elderly & hepatic impairment due to QT risk' },
  { id: 'm4-6', brandName: 'Effexor XR', genericName: 'Venlafaxine', drugClass: 'SNRI', indications: ['Depression', 'GAD', 'Social anxiety', 'Panic disorder'], commonDosing: '75-225 mg PO daily', sideEffects: ['Nausea', 'Hypertension', 'Discontinuation syndrome'], keyFact: 'Monitor BP; dose-dependent NE effects; taper slowly' },
  { id: 'm4-7', brandName: 'Cymbalta', genericName: 'Duloxetine', drugClass: 'SNRI', indications: ['Depression', 'Diabetic neuropathy', 'Fibromyalgia', 'Chronic pain'], commonDosing: '30-60 mg PO daily', sideEffects: ['Nausea', 'Dry mouth', 'Hepatotoxicity'], keyFact: 'Avoid in hepatic impairment & heavy alcohol use; good for pain' },

  // 4b: TCAs, Atypicals
  { id: 'm4-8', brandName: 'Elavil', genericName: 'Amitriptyline', drugClass: 'Tricyclic Antidepressant (TCA)', indications: ['Depression', 'Neuropathic pain', 'Migraine prophylaxis', 'Insomnia'], commonDosing: '25-150 mg PO at bedtime', sideEffects: ['Sedation', 'Anticholinergic effects', 'Weight gain', 'QT prolongation'], keyFact: 'Highly anticholinergic; lethal in overdose; Beers list (avoid in elderly)' },
  { id: 'm4-9', brandName: 'Pamelor', genericName: 'Nortriptyline', drugClass: 'Tricyclic Antidepressant (TCA)', indications: ['Depression', 'Neuropathic pain'], commonDosing: '25-150 mg PO daily', sideEffects: ['Sedation', 'Dry mouth', 'Constipation', 'Cardiac effects'], keyFact: 'Active metabolite of amitriptyline; less sedating than amitriptyline' },
  { id: 'm4-10', brandName: 'Wellbutrin', genericName: 'Bupropion', drugClass: 'NDRI (Norepinephrine-Dopamine Reuptake Inhibitor)', indications: ['Depression', 'Smoking cessation', 'Seasonal affective disorder'], commonDosing: '150-450 mg PO daily (divided for IR)', sideEffects: ['Insomnia', 'Seizure risk', 'Dry mouth'], keyFact: 'No sexual dysfunction; lowers seizure threshold; contraindicated in eating disorders' },
  { id: 'm4-11', brandName: 'Remeron', genericName: 'Mirtazapine', drugClass: 'Atypical Antidepressant (NaSSA)', indications: ['Depression', 'Insomnia', 'Appetite stimulation'], commonDosing: '15-45 mg PO at bedtime', sideEffects: ['Sedation', 'Weight gain', 'Increased appetite'], keyFact: 'More sedating at lower doses (15 mg) due to antihistamine effect' },
  { id: 'm4-12', brandName: 'Desyrel', genericName: 'Trazodone', drugClass: 'Serotonin Antagonist and Reuptake Inhibitor (SARI)', indications: ['Depression', 'Insomnia'], commonDosing: '50-100 mg PO at bedtime (insomnia); up to 400 mg (depression)', sideEffects: ['Sedation', 'Priapism', 'Orthostatic hypotension'], keyFact: 'Commonly used off-label for insomnia at low doses; priapism is rare but serious' },

  // 4c: Antipsychotics
  { id: 'm4-13', brandName: 'Seroquel', genericName: 'Quetiapine', drugClass: 'Atypical Antipsychotic', indications: ['Schizophrenia', 'Bipolar disorder', 'Adjunct depression'], commonDosing: '25-800 mg PO daily', sideEffects: ['Sedation', 'Weight gain', 'Metabolic syndrome'], keyFact: 'Most sedating atypical; monitor glucose, lipids & weight' },
  { id: 'm4-14', brandName: 'Abilify', genericName: 'Aripiprazole', drugClass: 'Atypical Antipsychotic (Partial D2 agonist)', indications: ['Schizophrenia', 'Bipolar', 'Adjunct MDD', 'Irritability in autism'], commonDosing: '2-30 mg PO daily', sideEffects: ['Akathisia', 'Insomnia', 'Restlessness'], keyFact: 'Partial dopamine agonist; fewer metabolic effects than others' },
  { id: 'm4-15', brandName: 'Risperdal', genericName: 'Risperidone', drugClass: 'Atypical Antipsychotic', indications: ['Schizophrenia', 'Bipolar', 'Irritability in autism'], commonDosing: '1-6 mg PO daily', sideEffects: ['Weight gain', 'Hyperprolactinemia', 'EPS'], keyFact: 'Highest prolactin elevation among atypicals; available as LAI (Risperdal Consta)' },
  { id: 'm4-16', brandName: 'Zyprexa', genericName: 'Olanzapine', drugClass: 'Atypical Antipsychotic', indications: ['Schizophrenia', 'Bipolar disorder'], commonDosing: '5-20 mg PO daily', sideEffects: ['Significant weight gain', 'Metabolic syndrome', 'Sedation'], keyFact: 'Highest metabolic risk; monitor glucose, lipids, weight closely' },
  { id: 'm4-17', brandName: 'Haldol', genericName: 'Haloperidol', drugClass: 'Typical Antipsychotic (1st generation)', indications: ['Schizophrenia', 'Acute psychosis', 'Tourette syndrome'], commonDosing: '0.5-20 mg PO/IM daily', sideEffects: ['EPS', 'Tardive dyskinesia', 'QT prolongation', 'NMS'], keyFact: 'High-potency typical; high EPS risk; gold standard for acute agitation' },

  // 4d: Anxiolytics & Sedatives
  { id: 'm4-18', brandName: 'Xanax', genericName: 'Alprazolam', drugClass: 'Benzodiazepine', indications: ['Anxiety disorders', 'Panic disorder'], commonDosing: '0.25-0.5 mg PO TID', sideEffects: ['Sedation', 'Dependence', 'Respiratory depression'], keyFact: 'Short-acting; high abuse potential; Schedule IV' },
  { id: 'm4-19', brandName: 'Ativan', genericName: 'Lorazepam', drugClass: 'Benzodiazepine', indications: ['Anxiety', 'Status epilepticus', 'Alcohol withdrawal'], commonDosing: '0.5-2 mg PO/IV q6-8h', sideEffects: ['Sedation', 'Respiratory depression', 'Paradoxical agitation'], keyFact: 'LOT drugs (Lorazepam, Oxazepam, Temazepam) - no hepatic CYP metabolism' },
  { id: 'm4-20', brandName: 'Valium', genericName: 'Diazepam', drugClass: 'Benzodiazepine', indications: ['Anxiety', 'Muscle spasm', 'Seizures', 'Alcohol withdrawal'], commonDosing: '2-10 mg PO BID-QID', sideEffects: ['Sedation', 'Dependence', 'Long half-life accumulation'], keyFact: 'Very long-acting (active metabolites up to 200 hr); Schedule IV' },
  { id: 'm4-21', brandName: 'Klonopin', genericName: 'Clonazepam', drugClass: 'Benzodiazepine', indications: ['Seizure disorders', 'Panic disorder'], commonDosing: '0.5-2 mg PO BID', sideEffects: ['Sedation', 'Ataxia', 'Dependence'], keyFact: 'Long-acting benzo also used as adjunct antiepileptic' },
  { id: 'm4-22', brandName: 'Ambien', genericName: 'Zolpidem', drugClass: 'Non-benzodiazepine Hypnotic (Z-drug)', indications: ['Insomnia'], commonDosing: '5-10 mg PO at bedtime (5 mg for women)', sideEffects: ['Somnambulism', 'Next-day impairment', 'Complex sleep behaviors'], keyFact: 'Lower dose recommended for women; Schedule IV' },
  { id: 'm4-23', brandName: 'Lunesta', genericName: 'Eszopiclone', drugClass: 'Non-benzodiazepine Hypnotic (Z-drug)', indications: ['Insomnia'], commonDosing: '1-3 mg PO at bedtime', sideEffects: ['Metallic taste', 'Headache', 'Drowsiness'], keyFact: 'No short-term use restriction; can be prescribed long-term' },
  { id: 'm4-24', brandName: 'Vistaril', genericName: 'Hydroxyzine', drugClass: 'Antihistamine (H1 blocker)', indications: ['Anxiety', 'Pruritus', 'Insomnia', 'Preoperative sedation'], commonDosing: '25-100 mg PO TID-QID', sideEffects: ['Sedation', 'Dry mouth', 'Dizziness'], keyFact: 'Non-habit-forming anxiolytic; parent compound of cetirizine' },

  // 4e: Stimulants & ADHD
  { id: 'm4-25', brandName: 'Ritalin/Concerta', genericName: 'Methylphenidate', drugClass: 'CNS Stimulant', indications: ['ADHD', 'Narcolepsy'], commonDosing: '5-20 mg PO BID-TID (IR); 18-72 mg daily (ER)', sideEffects: ['Insomnia', 'Decreased appetite', 'Tachycardia'], keyFact: 'Schedule II; monitor growth in children, HR, and BP' },
  { id: 'm4-26', brandName: 'Adderall', genericName: 'Amphetamine/Dextroamphetamine', drugClass: 'CNS Stimulant', indications: ['ADHD', 'Narcolepsy'], commonDosing: '5-30 mg PO daily-BID (IR); 10-30 mg daily (XR)', sideEffects: ['Insomnia', 'Decreased appetite', 'Anxiety', 'Tachycardia'], keyFact: 'Schedule II; mixed amphetamine salts; high abuse potential' },
  { id: 'm4-27', brandName: 'Vyvanse', genericName: 'Lisdexamfetamine', drugClass: 'CNS Stimulant (Prodrug)', indications: ['ADHD', 'Binge eating disorder'], commonDosing: '20-70 mg PO daily', sideEffects: ['Insomnia', 'Decreased appetite', 'Dry mouth'], keyFact: 'Prodrug of dextroamphetamine; Schedule II; lower abuse potential due to prodrug design' },
  { id: 'm4-28', brandName: 'Strattera', genericName: 'Atomoxetine', drugClass: 'Selective NRI (Non-stimulant)', indications: ['ADHD'], commonDosing: '40-100 mg PO daily', sideEffects: ['GI upset', 'Decreased appetite', 'Suicidal ideation (black box in pediatrics)'], keyFact: 'Non-stimulant; not a controlled substance; CYP2D6 substrate' },
  { id: 'm4-29', brandName: 'Intuniv', genericName: 'Guanfacine ER', drugClass: 'Central Alpha-2 Agonist', indications: ['ADHD'], commonDosing: '1-4 mg PO daily', sideEffects: ['Somnolence', 'Hypotension', 'Bradycardia'], keyFact: 'Non-stimulant for ADHD; taper to discontinue to avoid rebound HTN' },

  // MODULE 5 – Pain, Inflammation & Rheum
  // 5a: NSAIDs & Acetaminophen
  { id: 'm5-1', brandName: 'Tylenol', genericName: 'Acetaminophen', drugClass: 'Non-opioid Analgesic/Antipyretic', indications: ['Pain', 'Fever'], commonDosing: '325-1000 mg PO q4-6h (max 3-4 g/day)', sideEffects: ['Hepatotoxicity (overdose)', 'Rare skin reactions'], keyFact: 'Max 4 g/day (2 g in liver disease); N-acetylcysteine for overdose' },
  { id: 'm5-2', brandName: 'Advil/Motrin', genericName: 'Ibuprofen', drugClass: 'NSAID (Non-selective COX inhibitor)', indications: ['Pain', 'Inflammation', 'Fever'], commonDosing: '200-800 mg PO q6-8h', sideEffects: ['GI bleeding', 'Renal impairment', 'CV risk'], keyFact: 'Avoid in CKD, HF, and GI bleed history; OTC & Rx' },
  { id: 'm5-3', brandName: 'Aleve', genericName: 'Naproxen', drugClass: 'NSAID', indications: ['Pain', 'Inflammation', 'Dysmenorrhea'], commonDosing: '250-500 mg PO BID', sideEffects: ['GI bleeding', 'Renal impairment', 'CV risk'], keyFact: 'Longer half-life; BID dosing; may have lower CV risk among NSAIDs' },
  { id: 'm5-4', brandName: 'Celebrex', genericName: 'Celecoxib', drugClass: 'COX-2 Selective NSAID', indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Pain'], commonDosing: '100-200 mg PO BID', sideEffects: ['CV risk', 'GI effects (less than non-selective NSAIDs)'], keyFact: 'Lower GI risk but still has CV black box warning; sulfa allergy caution' },
  { id: 'm5-5', brandName: 'Mobic', genericName: 'Meloxicam', drugClass: 'NSAID (COX-2 preferential)', indications: ['Osteoarthritis', 'Rheumatoid arthritis'], commonDosing: '7.5-15 mg PO daily', sideEffects: ['GI upset', 'Renal impairment', 'CV risk'], keyFact: 'Once daily dosing; somewhat COX-2 preferential at low doses' },
  { id: 'm5-6', brandName: 'Voltaren', genericName: 'Diclofenac', drugClass: 'NSAID', indications: ['Pain', 'Inflammation', 'Osteoarthritis'], commonDosing: '50 mg PO BID-TID; topical 1% gel', sideEffects: ['GI bleeding', 'Hepatotoxicity', 'CV risk'], keyFact: 'Available as oral, topical gel, and patch; topical has fewer systemic effects' },
  { id: 'm5-7', brandName: 'Toradol', genericName: 'Ketorolac', drugClass: 'NSAID', indications: ['Moderate-severe acute pain'], commonDosing: '10 mg PO q4-6h or 15-30 mg IV/IM q6h (max 5 days)', sideEffects: ['GI bleeding', 'Renal impairment', 'Platelet dysfunction'], keyFact: 'Max 5 days total use; potent parenteral NSAID' },

  // 5b: Opioids
  { id: 'm5-8', brandName: 'Norco', genericName: 'Hydrocodone/Acetaminophen', drugClass: 'Opioid + Non-opioid Analgesic', indications: ['Moderate-severe pain'], commonDosing: '5/325 to 10/325 mg PO q4-6h', sideEffects: ['Constipation', 'Sedation', 'Respiratory depression'], keyFact: 'Schedule II; monitor total daily acetaminophen intake' },
  { id: 'm5-9', brandName: 'Percocet', genericName: 'Oxycodone/Acetaminophen', drugClass: 'Opioid + Non-opioid Analgesic', indications: ['Moderate-severe pain'], commonDosing: '5/325 mg PO q6h PRN', sideEffects: ['Constipation', 'N/V', 'Respiratory depression'], keyFact: 'Schedule II; high abuse potential' },
  { id: 'm5-10', brandName: 'MS Contin', genericName: 'Morphine', drugClass: 'Opioid Agonist', indications: ['Severe pain', 'Palliative care'], commonDosing: '15-30 mg PO q4h (IR); 15-200 mg PO q12h (ER)', sideEffects: ['Constipation', 'Respiratory depression', 'N/V', 'Histamine release'], keyFact: 'Gold standard opioid for comparison; renally excreted active metabolite' },
  { id: 'm5-11', brandName: 'Ultram', genericName: 'Tramadol', drugClass: 'Atypical Opioid (mu-agonist + SNRI)', indications: ['Moderate pain'], commonDosing: '50-100 mg PO q4-6h (max 400 mg/day)', sideEffects: ['Seizures', 'Serotonin syndrome', 'Constipation'], keyFact: 'Lowers seizure threshold; serotonergic properties; Schedule IV' },
  { id: 'm5-12', brandName: 'Tylenol #3', genericName: 'Codeine/Acetaminophen', drugClass: 'Opioid + Non-opioid Analgesic', indications: ['Mild-moderate pain', 'Cough'], commonDosing: '30/300 mg PO q4-6h', sideEffects: ['Constipation', 'N/V', 'Sedation'], keyFact: 'Prodrug via CYP2D6; ultra-rapid metabolizers at risk for toxicity' },
  { id: 'm5-13', brandName: 'Suboxone', genericName: 'Buprenorphine/Naloxone', drugClass: 'Partial Opioid Agonist + Antagonist', indications: ['Opioid use disorder'], commonDosing: '4/1 to 24/6 mg SL daily', sideEffects: ['Headache', 'N/V', 'Precipitated withdrawal (if given too early)'], keyFact: 'Partial mu agonist; ceiling effect on respiratory depression' },
  { id: 'm5-14', brandName: 'Narcan', genericName: 'Naloxone', drugClass: 'Opioid Antagonist', indications: ['Opioid overdose reversal'], commonDosing: '0.4-2 mg IV/IM/IN; may repeat q2-3min', sideEffects: ['Precipitated withdrawal', 'Tachycardia', 'N/V'], keyFact: 'Short duration (~30-90 min); may need repeat doses for long-acting opioids' },
  { id: 'm5-15', brandName: 'Vivitrol', genericName: 'Naltrexone', drugClass: 'Opioid Antagonist', indications: ['Opioid use disorder', 'Alcohol use disorder'], commonDosing: '50 mg PO daily or 380 mg IM monthly', sideEffects: ['Nausea', 'Headache', 'Hepatotoxicity'], keyFact: 'Must be opioid-free 7-10 days before starting; blocks opioid effects' },

  // 5c: Gout
  { id: 'm5-16', brandName: 'Zyloprim', genericName: 'Allopurinol', drugClass: 'Xanthine Oxidase Inhibitor', indications: ['Gout (chronic)', 'Hyperuricemia', 'Tumor lysis syndrome prophylaxis'], commonDosing: '100-800 mg PO daily (start low)', sideEffects: ['Rash', 'SJS/TEN (HLA-B*5801)', 'GI upset'], keyFact: 'Check HLA-B*5801 in at-risk populations before starting' },
  { id: 'm5-17', brandName: 'Uloric', genericName: 'Febuxostat', drugClass: 'Xanthine Oxidase Inhibitor', indications: ['Chronic gout'], commonDosing: '40-80 mg PO daily', sideEffects: ['CV events (black box)', 'Liver enzyme elevation', 'Nausea'], keyFact: 'Black box for increased CV death; use only if allopurinol fails/intolerant' },
  { id: 'm5-18', brandName: 'Colcrys', genericName: 'Colchicine', drugClass: 'Anti-inflammatory (Microtubule inhibitor)', indications: ['Gout flare', 'Gout prophylaxis', 'FMF'], commonDosing: '1.2 mg then 0.6 mg 1 hr later (acute); 0.6 mg daily-BID (prophylaxis)', sideEffects: ['Diarrhea', 'N/V', 'Bone marrow suppression (overdose)'], keyFact: 'Narrow therapeutic index; dose reduce with CYP3A4 inhibitors & renal impairment' },

  // 5d: DMARDs & Biologics
  { id: 'm5-19', brandName: 'Rheumatrex', genericName: 'Methotrexate', drugClass: 'DMARD (Antimetabolite)', indications: ['RA', 'Psoriasis', 'Ectopic pregnancy'], commonDosing: '7.5-25 mg PO/SC weekly', sideEffects: ['Hepatotoxicity', 'Bone marrow suppression', 'Pulmonary toxicity'], keyFact: 'Weekly dosing (daily is fatal error); give folic acid 1 mg daily' },
  { id: 'm5-20', brandName: 'Plaquenil', genericName: 'Hydroxychloroquine', drugClass: 'DMARD (Antimalarial)', indications: ['SLE', 'Rheumatoid arthritis'], commonDosing: '200-400 mg PO daily', sideEffects: ['Retinal toxicity', 'GI upset', 'QT prolongation'], keyFact: 'Annual eye exams for retinal toxicity screening after 5 years' },
  { id: 'm5-21', brandName: 'Azulfidine', genericName: 'Sulfasalazine', drugClass: 'DMARD (Aminosalicylate)', indications: ['RA', 'Ulcerative colitis'], commonDosing: '500-1500 mg PO BID', sideEffects: ['GI upset', 'Rash', 'Hepatotoxicity', 'Bone marrow suppression'], keyFact: 'Contains sulfa moiety; check G6PD; monitor CBC & LFTs' },
  { id: 'm5-22', brandName: 'Humira', genericName: 'Adalimumab', drugClass: 'TNF-alpha Inhibitor (Biologic)', indications: ['RA', 'Crohn disease', 'Psoriasis', 'UC'], commonDosing: '40 mg SC every other week', sideEffects: ['Infections', 'Injection site reactions', 'Lymphoma risk'], keyFact: 'Screen for TB and hepatitis B before starting any TNF inhibitor' },
  { id: 'm5-23', brandName: 'Enbrel', genericName: 'Etanercept', drugClass: 'TNF-alpha Inhibitor (Biologic)', indications: ['RA', 'Psoriatic arthritis', 'Ankylosing spondylitis'], commonDosing: '50 mg SC weekly', sideEffects: ['Infections', 'Injection site reactions', 'Demyelination'], keyFact: 'Soluble TNF receptor; less effective in Crohn disease than other anti-TNFs' },

  // 5e: Systemic Steroids in Rheum (references m3-25 Prednisone; add unique drug)
  { id: 'm5-24', brandName: 'Depo-Medrol', genericName: 'Methylprednisolone Acetate', drugClass: 'Injectable Corticosteroid', indications: ['Joint inflammation', 'Bursitis', 'Severe allergic reactions'], commonDosing: '20-80 mg intra-articular; 40-120 mg IM', sideEffects: ['Local joint destruction (repeated use)', 'Hyperglycemia', 'Skin atrophy'], keyFact: 'Intra-articular injections limited to 3-4 per year per joint' },

  // MODULE 6 – Infectious Disease
  // 6a: Strategy (overview lesson, uses drugs from 6b-6e)

  // 6b: Beta-Lactams
  { id: 'm6-1', brandName: 'Amoxil', genericName: 'Amoxicillin', drugClass: 'Aminopenicillin', indications: ['Otitis media', 'Sinusitis', 'UTI', 'H. pylori'], commonDosing: '500 mg PO TID or 875 mg PO BID', sideEffects: ['Diarrhea', 'Rash', 'N/V'], keyFact: 'Most commonly prescribed antibiotic in children' },
  { id: 'm6-2', brandName: 'Augmentin', genericName: 'Amoxicillin/Clavulanate', drugClass: 'Aminopenicillin + Beta-lactamase Inhibitor', indications: ['Sinusitis', 'Pneumonia', 'Bite wounds', 'UTI'], commonDosing: '875/125 mg PO BID', sideEffects: ['Diarrhea', 'N/V', 'Yeast infection'], keyFact: 'Clavulanate extends coverage to beta-lactamase producing organisms' },
  { id: 'm6-3', brandName: 'Unasyn', genericName: 'Ampicillin/Sulbactam', drugClass: 'Aminopenicillin + Beta-lactamase Inhibitor', indications: ['Intra-abdominal infections', 'Skin infections', 'Gynecologic infections'], commonDosing: '1.5-3 g IV/IM q6h', sideEffects: ['Diarrhea', 'Rash', 'Pain at injection site'], keyFact: 'IV formulation; good for polymicrobial infections' },
  { id: 'm6-4', brandName: 'Zosyn', genericName: 'Piperacillin/Tazobactam', drugClass: 'Extended-spectrum Penicillin + Beta-lactamase Inhibitor', indications: ['Nosocomial pneumonia', 'Intra-abdominal infections', 'Sepsis'], commonDosing: '3.375-4.5 g IV q6-8h', sideEffects: ['Diarrhea', 'Rash', 'Thrombocytopenia'], keyFact: 'Broad spectrum including Pseudomonas; renally dosed' },
  { id: 'm6-5', brandName: 'Keflex', genericName: 'Cephalexin', drugClass: '1st Gen Cephalosporin', indications: ['Skin infections', 'UTI', 'Strep pharyngitis'], commonDosing: '500 mg PO QID', sideEffects: ['GI upset', 'Rash', 'Allergic reaction'], keyFact: '~1-2% cross-reactivity with penicillin allergy' },
  { id: 'm6-6', brandName: 'Omnicef', genericName: 'Cefdinir', drugClass: '3rd Gen Cephalosporin (oral)', indications: ['Otitis media', 'Sinusitis', 'Pharyngitis', 'Pneumonia'], commonDosing: '300 mg PO BID or 600 mg PO daily', sideEffects: ['Diarrhea', 'Red-colored stool (with iron)', 'N/V'], keyFact: 'Can cause red stools when taken with iron; not drug-related bleeding' },
  { id: 'm6-7', brandName: 'Rocephin', genericName: 'Ceftriaxone', drugClass: '3rd Gen Cephalosporin (IV/IM)', indications: ['Meningitis', 'Pneumonia', 'Gonorrhea', 'Sepsis'], commonDosing: '1-2 g IV/IM daily', sideEffects: ['Diarrhea', 'Rash', 'Biliary sludging'], keyFact: 'Do not mix with calcium-containing IV solutions in neonates' },
  { id: 'm6-8', brandName: 'Maxipime', genericName: 'Cefepime', drugClass: '4th Gen Cephalosporin', indications: ['Febrile neutropenia', 'Nosocomial pneumonia', 'Pseudomonas infections'], commonDosing: '1-2 g IV q8-12h', sideEffects: ['Rash', 'Diarrhea', 'Neurotoxicity (esp. in renal impairment)'], keyFact: 'Covers Pseudomonas; dose adjust in renal impairment to avoid seizures' },

  // 6c: Macrolides, Fluoroquinolones, Tetracyclines
  { id: 'm6-9', brandName: 'Zithromax', genericName: 'Azithromycin', drugClass: 'Macrolide', indications: ['Community-acquired pneumonia', 'Sinusitis', 'Chlamydia'], commonDosing: '500 mg day 1 then 250 mg days 2-5 (Z-pack)', sideEffects: ['GI upset', 'QT prolongation', 'Hepatotoxicity'], keyFact: 'Z-pack is 5-day course; long tissue half-life; QT risk' },
  { id: 'm6-10', brandName: 'Biaxin', genericName: 'Clarithromycin', drugClass: 'Macrolide', indications: ['H. pylori', 'Sinusitis', 'MAC prophylaxis'], commonDosing: '250-500 mg PO BID', sideEffects: ['Metallic taste', 'GI upset', 'QT prolongation'], keyFact: 'Strong CYP3A4 inhibitor; many drug interactions; part of H. pylori triple therapy' },
  { id: 'm6-11', brandName: 'Cipro', genericName: 'Ciprofloxacin', drugClass: 'Fluoroquinolone', indications: ['UTI', 'Anthrax', 'Intra-abdominal infections'], commonDosing: '250-750 mg PO BID', sideEffects: ['Tendon rupture', 'QT prolongation', 'CNS effects'], keyFact: 'Black box for tendinitis/tendon rupture; avoid with antacids, dairy' },
  { id: 'm6-12', brandName: 'Levaquin', genericName: 'Levofloxacin', drugClass: 'Fluoroquinolone', indications: ['Pneumonia', 'Sinusitis', 'UTI'], commonDosing: '500-750 mg PO/IV daily', sideEffects: ['Tendon rupture', 'QT prolongation', 'Peripheral neuropathy'], keyFact: 'Respiratory FQ; covers atypicals and Strep pneumo' },
  { id: 'm6-13', brandName: 'Avelox', genericName: 'Moxifloxacin', drugClass: 'Fluoroquinolone', indications: ['Community-acquired pneumonia', 'Sinusitis', 'Skin infections'], commonDosing: '400 mg PO/IV daily', sideEffects: ['QT prolongation', 'Tendon rupture', 'C. diff'], keyFact: 'Highest QT prolongation risk among FQs; not renally adjusted' },
  { id: 'm6-14', brandName: 'Vibramycin', genericName: 'Doxycycline', drugClass: 'Tetracycline', indications: ['Acne', 'Chlamydia', 'Lyme disease', 'MRSA skin infections', 'Malaria prophylaxis'], commonDosing: '100 mg PO BID', sideEffects: ['Photosensitivity', 'GI upset', 'Esophageal ulceration'], keyFact: 'Take with full glass of water; avoid lying down 30 min after; no dairy restriction unlike other tetracyclines' },
  { id: 'm6-15', brandName: 'Minocin', genericName: 'Minocycline', drugClass: 'Tetracycline', indications: ['Acne', 'Skin infections', 'RA (off-label)'], commonDosing: '100 mg PO BID', sideEffects: ['Dizziness/vertigo', 'Skin discoloration', 'Photosensitivity'], keyFact: 'Can cause blue-gray skin discoloration with prolonged use' },

  // 6d: Sulfonamides & Others
  { id: 'm6-16', brandName: 'Bactrim', genericName: 'Sulfamethoxazole/Trimethoprim (TMP/SMX)', drugClass: 'Sulfonamide + DHFR Inhibitor', indications: ['UTI', 'MRSA skin infections', 'PJP prophylaxis'], commonDosing: '1 DS tab (800/160 mg) PO BID', sideEffects: ['Rash', 'Hyperkalemia', 'Bone marrow suppression'], keyFact: 'Covers MRSA; monitor potassium & renal function; sulfa allergy' },
  { id: 'm6-17', brandName: 'Macrobid', genericName: 'Nitrofurantoin', drugClass: 'Nitrofuran Antibiotic', indications: ['Uncomplicated UTI', 'UTI prophylaxis'], commonDosing: '100 mg PO BID x5 days', sideEffects: ['GI upset', 'Pulmonary toxicity (chronic use)', 'Peripheral neuropathy'], keyFact: 'Only works in lower urinary tract; avoid if CrCl <30 mL/min' },
  { id: 'm6-18', brandName: 'Flagyl', genericName: 'Metronidazole', drugClass: 'Nitroimidazole', indications: ['C. diff', 'Anaerobic infections', 'Trichomoniasis', 'H. pylori'], commonDosing: '500 mg PO/IV TID', sideEffects: ['Metallic taste', 'N/V', 'Disulfiram reaction'], keyFact: 'Avoid alcohol (disulfiram-like reaction); covers anaerobes' },
  { id: 'm6-19', brandName: 'Vancocin', genericName: 'Vancomycin', drugClass: 'Glycopeptide', indications: ['MRSA', 'C. diff (PO)', 'Endocarditis'], commonDosing: 'IV: 15-20 mg/kg q8-12h; PO: 125 mg QID (C. diff)', sideEffects: ['Nephrotoxicity', 'Red Man Syndrome', 'Ototoxicity'], keyFact: 'AUC/MIC guided dosing for IV; PO only works for C. diff (not absorbed)' },
  { id: 'm6-20', brandName: 'Zyvox', genericName: 'Linezolid', drugClass: 'Oxazolidinone', indications: ['MRSA', 'VRE', 'Pneumonia'], commonDosing: '600 mg PO/IV BID', sideEffects: ['Thrombocytopenia', 'Serotonin syndrome', 'Lactic acidosis'], keyFact: 'Weak MAO inhibitor; avoid tyramine-rich foods and serotonergic drugs' },
  { id: 'm6-21', brandName: 'Cleocin', genericName: 'Clindamycin', drugClass: 'Lincosamide', indications: ['Skin infections', 'Dental infections', 'MRSA', 'Anaerobes'], commonDosing: '150-450 mg PO QID or 600-900 mg IV q8h', sideEffects: ['C. diff colitis', 'Diarrhea', 'Rash'], keyFact: 'High C. diff risk; good for penicillin-allergic patients with skin infections' },

  // 6e: Antifungals & Antivirals
  { id: 'm6-22', brandName: 'Diflucan', genericName: 'Fluconazole', drugClass: 'Azole Antifungal', indications: ['Candidiasis', 'Cryptococcal meningitis'], commonDosing: '150 mg PO x1 (vaginal); 200-400 mg daily (systemic)', sideEffects: ['Hepatotoxicity', 'QT prolongation', 'GI upset'], keyFact: 'CYP2C9, 2C19, 3A4 inhibitor; many drug interactions' },
  { id: 'm6-23', brandName: 'Nystatin', genericName: 'Nystatin', drugClass: 'Polyene Antifungal', indications: ['Oral thrush', 'Cutaneous candidiasis'], commonDosing: '100,000 units/mL: swish and swallow QID', sideEffects: ['GI upset', 'Unpleasant taste'], keyFact: 'Not absorbed systemically; topical/local use only' },
  { id: 'm6-24', brandName: 'Zovirax', genericName: 'Acyclovir', drugClass: 'Nucleoside Analog Antiviral', indications: ['HSV', 'VZV (shingles)', 'Herpes encephalitis'], commonDosing: '200-800 mg PO 5x/day; 5-10 mg/kg IV q8h', sideEffects: ['Nephrotoxicity (IV)', 'N/V', 'Headache'], keyFact: 'Requires adequate hydration with IV dosing to prevent crystalluria' },
  { id: 'm6-25', brandName: 'Valtrex', genericName: 'Valacyclovir', drugClass: 'Nucleoside Analog Antiviral (Prodrug)', indications: ['HSV', 'VZV (shingles)', 'HSV suppression'], commonDosing: '500-1000 mg PO BID-TID', sideEffects: ['Headache', 'N/V', 'TTP/HUS (high doses in immunocompromised)'], keyFact: 'Prodrug of acyclovir; better oral bioavailability; less frequent dosing' },
  { id: 'm6-26', brandName: 'Tamiflu', genericName: 'Oseltamivir', drugClass: 'Neuraminidase Inhibitor', indications: ['Influenza A & B treatment/prophylaxis'], commonDosing: '75 mg PO BID x5 days (treatment)', sideEffects: ['N/V', 'Headache', 'Neuropsychiatric events (rare)'], keyFact: 'Most effective if started within 48 hrs of symptom onset' },

  // MODULE 7 – Respiratory & Allergy
  // 7a: Overview (uses drugs from 7b-7e)

  // 7b: Inhaled Bronchodilators
  { id: 'm7-1', brandName: 'ProAir/Ventolin', genericName: 'Albuterol', drugClass: 'Short-acting Beta-2 Agonist (SABA)', indications: ['Asthma (rescue)', 'Bronchospasm', 'COPD'], commonDosing: '2 puffs q4-6h PRN (MDI); 2.5 mg nebulized q4-6h', sideEffects: ['Tachycardia', 'Tremor', 'Hypokalemia'], keyFact: 'First-line rescue inhaler for acute bronchospasm' },
  { id: 'm7-2', brandName: 'Atrovent', genericName: 'Ipratropium', drugClass: 'Short-acting Muscarinic Antagonist (SAMA)', indications: ['COPD', 'Acute bronchospasm (combined with SABA)'], commonDosing: '2 puffs QID (MDI); 0.5 mg nebulized q6-8h', sideEffects: ['Dry mouth', 'Dizziness', 'Urinary retention'], keyFact: 'Often combined with albuterol in DuoNeb/Combivent for acute COPD' },
  { id: 'm7-3', brandName: 'Spiriva', genericName: 'Tiotropium', drugClass: 'Long-acting Muscarinic Antagonist (LAMA)', indications: ['COPD maintenance', 'Asthma (add-on)'], commonDosing: '18 mcg INH daily (HandiHaler) or 2.5 mcg daily (Respimat)', sideEffects: ['Dry mouth', 'Constipation', 'Urinary retention'], keyFact: 'Cornerstone of COPD maintenance; once-daily dosing' },
  { id: 'm7-4', brandName: 'Serevent', genericName: 'Salmeterol', drugClass: 'Long-acting Beta-2 Agonist (LABA)', indications: ['Asthma (with ICS)', 'COPD'], commonDosing: '50 mcg INH BID', sideEffects: ['Tachycardia', 'Tremor', 'Headache'], keyFact: 'Never use LABA alone in asthma (black box); always with ICS' },
  { id: 'm7-5', brandName: 'Foradil', genericName: 'Formoterol', drugClass: 'Long-acting Beta-2 Agonist (LABA)', indications: ['Asthma (with ICS)', 'COPD', 'Exercise-induced bronchospasm'], commonDosing: '12 mcg INH BID', sideEffects: ['Tachycardia', 'Tremor', 'Hypokalemia'], keyFact: 'Fast onset LABA; used in combination inhalers (Symbicort)' },

  // 7c: ICS & Combos
  { id: 'm7-6', brandName: 'Flovent', genericName: 'Fluticasone (inhaled)', drugClass: 'Inhaled Corticosteroid (ICS)', indications: ['Asthma maintenance'], commonDosing: '44-220 mcg INH BID', sideEffects: ['Oral candidiasis', 'Dysphonia', 'Adrenal suppression'], keyFact: 'Rinse mouth after use to prevent thrush; controller, not rescue' },
  { id: 'm7-7', brandName: 'Pulmicort', genericName: 'Budesonide (inhaled)', drugClass: 'Inhaled Corticosteroid (ICS)', indications: ['Asthma maintenance', 'Croup'], commonDosing: '180-360 mcg INH BID; 0.25-1 mg nebulized', sideEffects: ['Oral candidiasis', 'Cough', 'Dysphonia'], keyFact: 'Available as nebulization for young children; preferred ICS in pregnancy' },
  { id: 'm7-8', brandName: 'Advair', genericName: 'Fluticasone/Salmeterol', drugClass: 'ICS + LABA Combination', indications: ['Asthma', 'COPD'], commonDosing: '1 inhalation BID (various strengths)', sideEffects: ['Oral candidiasis', 'Tachycardia', 'Headache'], keyFact: 'ICS+LABA combo; LABA should never be used alone in asthma' },
  { id: 'm7-9', brandName: 'Symbicort', genericName: 'Budesonide/Formoterol', drugClass: 'ICS + LABA Combination', indications: ['Asthma', 'COPD'], commonDosing: '2 puffs BID (80/4.5 or 160/4.5 mcg)', sideEffects: ['Oral candidiasis', 'Headache', 'Tremor'], keyFact: 'Can be used as both maintenance and reliever therapy (SMART approach)' },

  // 7d: Leukotriene Modifiers & Controllers
  { id: 'm7-10', brandName: 'Singulair', genericName: 'Montelukast', drugClass: 'Leukotriene Receptor Antagonist', indications: ['Asthma', 'Allergic rhinitis', 'Exercise-induced bronchospasm'], commonDosing: '10 mg PO daily at bedtime', sideEffects: ['Headache', 'Neuropsychiatric events', 'GI upset'], keyFact: 'Black box warning for neuropsychiatric events (mood changes, suicidality)' },
  { id: 'm7-11', brandName: 'Theo-Dur', genericName: 'Theophylline', drugClass: 'Methylxanthine Bronchodilator', indications: ['Asthma', 'COPD'], commonDosing: '200-400 mg PO BID (ER; titrate to serum levels 5-15 mcg/mL)', sideEffects: ['Tachycardia', 'Seizures', 'N/V', 'Arrhythmias'], keyFact: 'Narrow therapeutic index; monitor levels; many drug interactions (CYP1A2)' },

  // 7e: Antihistamines & Nasal Steroids
  { id: 'm7-12', brandName: 'Zyrtec', genericName: 'Cetirizine', drugClass: '2nd Gen Antihistamine (H1 blocker)', indications: ['Allergic rhinitis', 'Urticaria'], commonDosing: '5-10 mg PO daily', sideEffects: ['Drowsiness (mild)', 'Dry mouth', 'Headache'], keyFact: 'Less sedating than 1st gen but more sedating than loratadine/fexofenadine' },
  { id: 'm7-13', brandName: 'Claritin', genericName: 'Loratadine', drugClass: '2nd Gen Antihistamine (H1 blocker)', indications: ['Allergic rhinitis', 'Urticaria'], commonDosing: '10 mg PO daily', sideEffects: ['Headache', 'Dry mouth', 'Fatigue'], keyFact: 'Non-sedating; OTC available; active metabolite is desloratadine' },
  { id: 'm7-14', brandName: 'Allegra', genericName: 'Fexofenadine', drugClass: '2nd Gen Antihistamine (H1 blocker)', indications: ['Allergic rhinitis', 'Urticaria'], commonDosing: '60 mg PO BID or 180 mg PO daily', sideEffects: ['Headache', 'Nausea', 'Dysmenorrhea'], keyFact: 'Least sedating 2nd gen antihistamine; avoid with fruit juice (reduces absorption)' },
  { id: 'm7-15', brandName: 'Benadryl', genericName: 'Diphenhydramine', drugClass: '1st Gen Antihistamine (H1 blocker)', indications: ['Allergic reactions', 'Insomnia', 'Motion sickness'], commonDosing: '25-50 mg PO q4-6h', sideEffects: ['Sedation', 'Anticholinergic effects', 'Dry mouth'], keyFact: 'Highly sedating; Beers list (avoid in elderly); also used as sleep aid OTC' },
  { id: 'm7-16', brandName: 'Flonase', genericName: 'Fluticasone (nasal)', drugClass: 'Intranasal Corticosteroid', indications: ['Allergic rhinitis', 'Nasal polyps'], commonDosing: '1-2 sprays per nostril daily', sideEffects: ['Epistaxis', 'Headache', 'Nasal irritation'], keyFact: 'First-line for allergic rhinitis; OTC; takes days for full effect' },
  { id: 'm7-17', brandName: 'Nasonex', genericName: 'Mometasone (nasal)', drugClass: 'Intranasal Corticosteroid', indications: ['Allergic rhinitis', 'Nasal polyps'], commonDosing: '2 sprays per nostril daily', sideEffects: ['Epistaxis', 'Headache', 'Pharyngitis'], keyFact: 'Minimal systemic absorption; safe for long-term use' },

  // MODULE 8 – GI & Hepatic
  // 8a: PPIs & H2 Blockers
  { id: 'm8-1', brandName: 'Prilosec', genericName: 'Omeprazole', drugClass: 'Proton Pump Inhibitor (PPI)', indications: ['GERD', 'Peptic ulcer', 'H. pylori (combo)'], commonDosing: '20-40 mg PO daily', sideEffects: ['C. diff risk', 'Hypomagnesemia', 'Fracture risk'], keyFact: 'Take 30 min before meals; long-term risks (fracture, B12, Mg, C. diff)' },
  { id: 'm8-2', brandName: 'Nexium', genericName: 'Esomeprazole', drugClass: 'Proton Pump Inhibitor (PPI)', indications: ['GERD', 'Erosive esophagitis', 'Zollinger-Ellison'], commonDosing: '20-40 mg PO daily', sideEffects: ['Headache', 'GI effects', 'Hypomagnesemia'], keyFact: 'S-isomer of omeprazole; similar efficacy' },
  { id: 'm8-3', brandName: 'Protonix', genericName: 'Pantoprazole', drugClass: 'Proton Pump Inhibitor (PPI)', indications: ['GERD', 'Erosive esophagitis', 'Zollinger-Ellison'], commonDosing: '40 mg PO/IV daily', sideEffects: ['Headache', 'Diarrhea', 'Hypomagnesemia'], keyFact: 'IV formulation commonly used in hospital; fewer CYP2C19 interactions than omeprazole' },
  { id: 'm8-4', brandName: 'Prevacid', genericName: 'Lansoprazole', drugClass: 'Proton Pump Inhibitor (PPI)', indications: ['GERD', 'Peptic ulcer', 'H. pylori (combo)'], commonDosing: '15-30 mg PO daily', sideEffects: ['Headache', 'Diarrhea', 'Abdominal pain'], keyFact: 'Available as disintegrating tablet for patients who cannot swallow' },
  { id: 'm8-5', brandName: 'Pepcid', genericName: 'Famotidine', drugClass: 'H2 Receptor Antagonist', indications: ['GERD', 'Peptic ulcer', 'Heartburn'], commonDosing: '20-40 mg PO BID', sideEffects: ['Headache', 'Dizziness', 'Constipation'], keyFact: 'Safer long-term than PPIs; good alternative for mild GERD' },

  // 8b: Antiemetics
  { id: 'm8-6', brandName: 'Zofran', genericName: 'Ondansetron', drugClass: '5-HT3 Receptor Antagonist', indications: ['Nausea/Vomiting (chemo, post-op, pregnancy)'], commonDosing: '4-8 mg PO/IV q8h', sideEffects: ['Headache', 'Constipation', 'QT prolongation'], keyFact: 'First-line antiemetic; check QT interval at high doses' },
  { id: 'm8-7', brandName: 'Reglan', genericName: 'Metoclopramide', drugClass: 'Dopamine Antagonist/Prokinetic', indications: ['Gastroparesis', 'GERD', 'N/V'], commonDosing: '5-10 mg PO QID before meals', sideEffects: ['Tardive dyskinesia', 'EPS', 'Drowsiness'], keyFact: 'Black box: tardive dyskinesia with prolonged use >12 weeks' },
  { id: 'm8-8', brandName: 'Phenergan', genericName: 'Promethazine', drugClass: 'Phenothiazine Antiemetic/Antihistamine', indications: ['N/V', 'Motion sickness', 'Allergic reactions'], commonDosing: '12.5-25 mg PO/IM/IV q4-6h', sideEffects: ['Sedation', 'EPS', 'Tissue necrosis (IV extravasation)'], keyFact: 'Black box for IV use in children <2; avoid IV push (tissue necrosis risk)' },
  { id: 'm8-9', brandName: 'Compazine', genericName: 'Prochlorperazine', drugClass: 'Phenothiazine Antiemetic', indications: ['N/V', 'Migraine'], commonDosing: '5-10 mg PO/IV q6-8h', sideEffects: ['EPS', 'Sedation', 'Tardive dyskinesia'], keyFact: 'Also used for migraine in the ED; watch for dystonic reactions' },
  { id: 'm8-10', brandName: 'Transderm Scōp', genericName: 'Scopolamine', drugClass: 'Anticholinergic Antiemetic', indications: ['Motion sickness', 'Postoperative N/V'], commonDosing: '1.5 mg patch behind ear q72h', sideEffects: ['Dry mouth', 'Drowsiness', 'Blurred vision'], keyFact: 'Apply 4 hours before travel; transdermal patch; anticholinergic effects' },

  // 8c: Laxatives & Antidiarrheals
  { id: 'm8-11', brandName: 'Miralax', genericName: 'Polyethylene Glycol 3350', drugClass: 'Osmotic Laxative', indications: ['Constipation'], commonDosing: '17 g PO daily in 8 oz liquid', sideEffects: ['Bloating', 'Cramping', 'Diarrhea'], keyFact: 'Well tolerated; takes 1-3 days for effect; OTC' },
  { id: 'm8-12', brandName: 'Colace', genericName: 'Docusate Sodium', drugClass: 'Stool Softener', indications: ['Constipation prevention'], commonDosing: '100 mg PO BID', sideEffects: ['Mild cramping', 'Diarrhea'], keyFact: 'Stool softener only; minimal evidence for efficacy; commonly used with opioids' },
  { id: 'm8-13', brandName: 'Dulcolax', genericName: 'Bisacodyl', drugClass: 'Stimulant Laxative', indications: ['Constipation', 'Bowel prep'], commonDosing: '5-15 mg PO daily or 10 mg PR', sideEffects: ['Cramping', 'Diarrhea', 'Electrolyte imbalance'], keyFact: 'Do not crush enteric-coated tablets; avoid with dairy or antacids' },
  { id: 'm8-14', brandName: 'Senokot', genericName: 'Senna', drugClass: 'Stimulant Laxative', indications: ['Constipation', 'Opioid-induced constipation'], commonDosing: '8.6-17.2 mg PO at bedtime', sideEffects: ['Cramping', 'Diarrhea', 'Brown urine'], keyFact: 'Recommended prophylactic laxative with chronic opioid use' },
  { id: 'm8-15', brandName: 'Enulose', genericName: 'Lactulose', drugClass: 'Osmotic Laxative', indications: ['Constipation', 'Hepatic encephalopathy'], commonDosing: '15-30 mL PO daily (constipation); 30-45 mL q1-2h then TID (HE)', sideEffects: ['Bloating', 'Flatulence', 'Diarrhea'], keyFact: 'Goal 2-3 soft stools/day for hepatic encephalopathy' },
  { id: 'm8-16', brandName: 'Imodium', genericName: 'Loperamide', drugClass: 'Peripheral Opioid Agonist', indications: ['Diarrhea'], commonDosing: '4 mg initially, then 2 mg after each loose stool (max 16 mg/day)', sideEffects: ['Constipation', 'Abdominal pain', 'Cardiac toxicity (overdose)'], keyFact: 'Does not cross BBB at normal doses; avoid in C. diff or bloody diarrhea' },

  // 8d: Antispasmodics
  { id: 'm8-17', brandName: 'Bentyl', genericName: 'Dicyclomine', drugClass: 'Anticholinergic Antispasmodic', indications: ['Irritable bowel syndrome'], commonDosing: '10-20 mg PO QID', sideEffects: ['Dry mouth', 'Dizziness', 'Blurred vision'], keyFact: 'Anticholinergic; avoid in elderly per Beers criteria' },
  { id: 'm8-18', brandName: 'Levsin', genericName: 'Hyoscyamine', drugClass: 'Anticholinergic Antispasmodic', indications: ['IBS', 'GI spasm', 'Urinary spasm'], commonDosing: '0.125-0.25 mg PO/SL q4h', sideEffects: ['Dry mouth', 'Urinary retention', 'Tachycardia'], keyFact: 'Active L-isomer of atropine; Beers list—avoid in elderly' },

  // 8e: IBD & Liver
  { id: 'm8-19', brandName: 'Asacol/Lialda', genericName: 'Mesalamine', drugClass: '5-Aminosalicylate (5-ASA)', indications: ['Ulcerative colitis', 'Crohn disease (mild)'], commonDosing: '800 mg-1.2 g PO TID (formulation dependent)', sideEffects: ['Headache', 'GI upset', 'Nephrotoxicity (rare)'], keyFact: 'Multiple formulations target different GI locations; monitor renal function' },
  { id: 'm8-20', brandName: 'Remicade', genericName: 'Infliximab', drugClass: 'TNF-alpha Inhibitor (Biologic)', indications: ['Crohn disease', 'Ulcerative colitis', 'RA', 'Psoriasis'], commonDosing: '5 mg/kg IV at 0, 2, 6 weeks then q8 weeks', sideEffects: ['Infections', 'Infusion reactions', 'Hepatotoxicity'], keyFact: 'Chimeric monoclonal antibody; screen for TB and Hep B before starting' },
  { id: 'm8-21', brandName: 'Xifaxan', genericName: 'Rifaximin', drugClass: 'Rifamycin Antibiotic', indications: ['Hepatic encephalopathy', 'IBS-D', 'Traveler\'s diarrhea'], commonDosing: '550 mg PO BID (HE); 200 mg PO TID x3 days (TD)', sideEffects: ['Peripheral edema', 'Nausea', 'Dizziness'], keyFact: 'Non-absorbed; works locally in the GI tract; used with lactulose for HE' },
  { id: 'm8-22', brandName: 'Actigall', genericName: 'Ursodiol', drugClass: 'Bile Acid', indications: ['Gallstone dissolution', 'Primary biliary cholangitis'], commonDosing: '8-15 mg/kg/day PO in divided doses', sideEffects: ['Diarrhea', 'GI upset', 'Headache'], keyFact: 'Reduces cholesterol content in bile; used in PBC to slow progression' },

  // MODULE 9 – Neuro & Seizure
  // 9a: Overview (uses drugs from 9b-9e)

  // 9b: Classic Antiepileptics
  { id: 'm9-1', brandName: 'Dilantin', genericName: 'Phenytoin', drugClass: 'Hydantoin Antiepileptic', indications: ['Seizures (tonic-clonic, partial)', 'Status epilepticus'], commonDosing: '100 mg PO TID or 300 mg PO daily (ER)', sideEffects: ['Gingival hyperplasia', 'Hirsutism', 'Ataxia', 'SJS/TEN'], keyFact: 'Zero-order kinetics; small dose changes cause big level changes; monitor levels' },
  { id: 'm9-2', brandName: 'Depakote', genericName: 'Valproic Acid/Divalproex', drugClass: 'Broad-spectrum Antiepileptic', indications: ['Seizures', 'Bipolar disorder', 'Migraine prophylaxis'], commonDosing: '250-500 mg PO BID-TID (target level 50-100 mcg/mL)', sideEffects: ['Hepatotoxicity', 'Pancreatitis', 'Thrombocytopenia', 'Weight gain', 'Neural tube defects'], keyFact: 'Black box: hepatotoxicity, pancreatitis, teratogenicity; category X in pregnancy' },
  { id: 'm9-3', brandName: 'Tegretol', genericName: 'Carbamazepine', drugClass: 'Iminostilbene Antiepileptic', indications: ['Seizures (partial, tonic-clonic)', 'Trigeminal neuralgia', 'Bipolar'], commonDosing: '200 mg PO BID, titrate (target level 4-12 mcg/mL)', sideEffects: ['Aplastic anemia', 'SJS/TEN', 'SIADH', 'Dizziness'], keyFact: 'Potent CYP3A4 inducer (auto-induces own metabolism); check HLA-B*1502 in at-risk populations' },

  // 9c: Newer Antiepileptics
  { id: 'm9-4', brandName: 'Keppra', genericName: 'Levetiracetam', drugClass: 'SV2A Ligand Antiepileptic', indications: ['Seizures (partial, tonic-clonic, myoclonic)'], commonDosing: '500-1500 mg PO/IV BID', sideEffects: ['Irritability/behavioral changes', 'Somnolence', 'Dizziness'], keyFact: 'Renal elimination; no significant drug interactions; first-line in many guidelines' },
  { id: 'm9-5', brandName: 'Lamictal', genericName: 'Lamotrigine', drugClass: 'Sodium Channel Blocker Antiepileptic', indications: ['Seizures', 'Bipolar disorder (maintenance)'], commonDosing: '25-200 mg PO BID (slow titration over weeks)', sideEffects: ['SJS/TEN (esp. with rapid titration)', 'Headache', 'Dizziness'], keyFact: 'Very slow titration required to avoid SJS; valproate doubles lamotrigine levels' },
  { id: 'm9-6', brandName: 'Topamax', genericName: 'Topiramate', drugClass: 'Multiple MOA Antiepileptic', indications: ['Seizures', 'Migraine prophylaxis', 'Weight loss (off-label)'], commonDosing: '25-200 mg PO BID (seizures); 50-100 mg daily (migraine)', sideEffects: ['Cognitive slowing ("Dopamax")', 'Kidney stones', 'Metabolic acidosis', 'Weight loss'], keyFact: 'Causes word-finding difficulty; avoid in pregnancy (cleft palate risk)' },
  { id: 'm9-7', brandName: 'Neurontin', genericName: 'Gabapentin', drugClass: 'GABA Analog (Gabapentinoid)', indications: ['Neuropathic pain', 'Seizures (adjunct)', 'Postherpetic neuralgia'], commonDosing: '300-1200 mg PO TID', sideEffects: ['Sedation', 'Dizziness', 'Peripheral edema'], keyFact: 'Renal dose adjustment; saturable absorption; scheduled in some states' },
  { id: 'm9-8', brandName: 'Lyrica', genericName: 'Pregabalin', drugClass: 'GABA Analog (Gabapentinoid)', indications: ['Neuropathic pain', 'Fibromyalgia', 'Seizures (adjunct)'], commonDosing: '75-300 mg PO BID', sideEffects: ['Sedation', 'Weight gain', 'Peripheral edema'], keyFact: 'Schedule V; linear pharmacokinetics (unlike gabapentin); renal dosing' },
  { id: 'm9-9', brandName: 'Trileptal', genericName: 'Oxcarbazepine', drugClass: 'Antiepileptic (Carbamazepine analog)', indications: ['Seizures (partial)'], commonDosing: '300-600 mg PO BID', sideEffects: ['Hyponatremia', 'Dizziness', 'Somnolence'], keyFact: 'Less enzyme induction than carbamazepine; higher risk of hyponatremia' },

  // 9d: Migraine
  { id: 'm9-10', brandName: 'Imitrex', genericName: 'Sumatriptan', drugClass: '5-HT1B/1D Agonist (Triptan)', indications: ['Acute migraine', 'Cluster headache'], commonDosing: '25-100 mg PO; 6 mg SC; 5-20 mg nasal', sideEffects: ['Chest tightness', 'Tingling', 'Flushing'], keyFact: 'Contraindicated with ergotamines and within 2 weeks of MAOIs; avoid in CV disease' },
  { id: 'm9-11', brandName: 'Maxalt', genericName: 'Rizatriptan', drugClass: '5-HT1B/1D Agonist (Triptan)', indications: ['Acute migraine'], commonDosing: '5-10 mg PO; may repeat in 2 hrs (max 30 mg/day)', sideEffects: ['Dizziness', 'Somnolence', 'Chest tightness'], keyFact: 'Reduce dose to 5 mg with propranolol; fastest onset oral triptan' },
  { id: 'm9-12', brandName: 'Aimovig', genericName: 'Erenumab', drugClass: 'CGRP Receptor Antagonist', indications: ['Migraine prophylaxis'], commonDosing: '70-140 mg SC monthly', sideEffects: ['Injection site reactions', 'Constipation', 'Muscle spasm'], keyFact: 'First FDA-approved CGRP inhibitor for migraine prevention' },

  // 9e: Parkinson's
  { id: 'm9-13', brandName: 'Sinemet', genericName: 'Carbidopa/Levodopa', drugClass: 'Dopamine Precursor + Decarboxylase Inhibitor', indications: ['Parkinson disease'], commonDosing: '25/100 mg PO TID, titrate', sideEffects: ['Dyskinesia', 'N/V', 'Orthostatic hypotension', 'On-off phenomenon'], keyFact: 'Gold standard for PD; carbidopa prevents peripheral conversion of levodopa' },
  { id: 'm9-14', brandName: 'Mirapex', genericName: 'Pramipexole', drugClass: 'Dopamine Agonist (Non-ergot)', indications: ['Parkinson disease', 'Restless legs syndrome'], commonDosing: '0.125-1.5 mg PO TID (PD)', sideEffects: ['Somnolence', 'Impulse control disorders', 'Hallucinations', 'Orthostatic hypotension'], keyFact: 'Watch for pathological gambling, hypersexuality, compulsive eating' },
  { id: 'm9-15', brandName: 'Requip', genericName: 'Ropinirole', drugClass: 'Dopamine Agonist (Non-ergot)', indications: ['Parkinson disease', 'Restless legs syndrome'], commonDosing: '0.25-8 mg PO TID (PD)', sideEffects: ['Somnolence', 'Impulse control disorders', 'N/V'], keyFact: 'Similar to pramipexole; CYP1A2 substrate (ciprofloxacin interaction)' },
  { id: 'm9-16', brandName: 'Azilect', genericName: 'Rasagiline', drugClass: 'MAO-B Inhibitor', indications: ['Parkinson disease (monotherapy or adjunct)'], commonDosing: '0.5-1 mg PO daily', sideEffects: ['Headache', 'Orthostatic hypotension', 'Dyskinesia (adjunct)'], keyFact: 'Selective MAO-B inhibitor; avoid with meperidine and serotonergic drugs' },
  { id: 'm9-17', brandName: 'Comtan', genericName: 'Entacapone', drugClass: 'COMT Inhibitor', indications: ['Parkinson disease (adjunct to carbidopa/levodopa)'], commonDosing: '200 mg PO with each levodopa dose (max 8 doses/day)', sideEffects: ['Dyskinesia', 'Diarrhea', 'Orange-brown urine'], keyFact: 'Extends levodopa duration; combined with C/L in Stalevo' },
  { id: 'm9-18', brandName: 'Symmetrel', genericName: 'Amantadine', drugClass: 'NMDA Antagonist/Dopamine Releaser', indications: ['Parkinson disease', 'Levodopa-induced dyskinesia', 'Influenza A (historical)'], commonDosing: '100 mg PO BID', sideEffects: ['Livedo reticularis', 'Hallucinations', 'Edema'], keyFact: 'Useful for levodopa-induced dyskinesia; anticholinergic properties' },

  // MODULE 10 – GU, End-Organs & Misc
  // 10a: BPH & OAB
  { id: 'm10-1', brandName: 'Flomax', genericName: 'Tamsulosin', drugClass: 'Alpha-1A Blocker', indications: ['BPH'], commonDosing: '0.4 mg PO daily 30 min after meal', sideEffects: ['Orthostatic hypotension', 'Retrograde ejaculation', 'Floppy iris syndrome'], keyFact: 'Alpha-1A selective; less hypotension than non-selective alpha blockers' },
  { id: 'm10-2', brandName: 'Proscar', genericName: 'Finasteride', drugClass: '5-Alpha Reductase Inhibitor (Type II)', indications: ['BPH', 'Male pattern baldness'], commonDosing: '5 mg PO daily (BPH); 1 mg daily (hair loss as Propecia)', sideEffects: ['Sexual dysfunction', 'Decreased PSA', 'Gynecomastia'], keyFact: 'Lowers PSA by ~50%; takes months for BPH benefit; teratogenic—women should not handle' },
  { id: 'm10-3', brandName: 'Avodart', genericName: 'Dutasteride', drugClass: '5-Alpha Reductase Inhibitor (Type I & II)', indications: ['BPH'], commonDosing: '0.5 mg PO daily', sideEffects: ['Sexual dysfunction', 'Decreased PSA', 'Gynecomastia'], keyFact: 'Inhibits both type I & II 5-AR; very long half-life (~5 weeks)' },
  { id: 'm10-4', brandName: 'Uroxatral', genericName: 'Alfuzosin', drugClass: 'Alpha-1 Blocker', indications: ['BPH'], commonDosing: '10 mg PO daily after meal', sideEffects: ['Dizziness', 'Hypotension', 'Headache'], keyFact: 'ER formulation; less selective than tamsulosin; avoid in hepatic impairment' },
  { id: 'm10-5', brandName: 'Ditropan', genericName: 'Oxybutynin', drugClass: 'Antimuscarinic', indications: ['Overactive bladder'], commonDosing: '5 mg PO BID-TID (IR); 5-30 mg daily (ER)', sideEffects: ['Dry mouth', 'Constipation', 'Cognitive impairment (elderly)'], keyFact: 'High anticholinergic burden; Beers list; available as topical gel/patch' },
  { id: 'm10-6', brandName: 'Detrol LA', genericName: 'Tolterodine', drugClass: 'Antimuscarinic', indications: ['Overactive bladder'], commonDosing: '4 mg ER PO daily', sideEffects: ['Dry mouth', 'Constipation', 'Blurred vision'], keyFact: 'ER formulation has fewer side effects; Beers list in elderly' },
  { id: 'm10-7', brandName: 'Myrbetriq', genericName: 'Mirabegron', drugClass: 'Beta-3 Agonist', indications: ['Overactive bladder'], commonDosing: '25-50 mg PO daily', sideEffects: ['Hypertension', 'UTI', 'Headache'], keyFact: 'Non-anticholinergic alternative for OAB; preferred in elderly' },
  { id: 'm10-8', brandName: 'Vesicare', genericName: 'Solifenacin', drugClass: 'Antimuscarinic', indications: ['Overactive bladder'], commonDosing: '5-10 mg PO daily', sideEffects: ['Dry mouth', 'Constipation', 'Blurred vision'], keyFact: 'Long-acting antimuscarinic; once daily dosing' },

  // 10b: Osteoporosis & Bone Health
  { id: 'm10-9', brandName: 'Fosamax', genericName: 'Alendronate', drugClass: 'Bisphosphonate', indications: ['Osteoporosis treatment & prevention'], commonDosing: '10 mg PO daily or 70 mg PO weekly', sideEffects: ['Esophagitis', 'Osteonecrosis of jaw', 'Atypical femur fracture'], keyFact: 'Take on empty stomach with full glass of water; remain upright 30 min' },
  { id: 'm10-10', brandName: 'Actonel', genericName: 'Risedronate', drugClass: 'Bisphosphonate', indications: ['Osteoporosis treatment & prevention'], commonDosing: '5 mg PO daily or 35 mg PO weekly', sideEffects: ['GI upset', 'Osteonecrosis of jaw', 'Atypical fracture'], keyFact: 'Similar to alendronate; also available as monthly and delayed-release formulations' },
  { id: 'm10-11', brandName: 'Reclast', genericName: 'Zoledronic Acid', drugClass: 'Bisphosphonate (IV)', indications: ['Osteoporosis', 'Paget disease', 'Hypercalcemia of malignancy'], commonDosing: '5 mg IV once yearly (osteoporosis)', sideEffects: ['Flu-like symptoms', 'Renal toxicity', 'ONJ'], keyFact: 'Once yearly IV infusion; ensure adequate CrCl and hydration before infusion' },
  { id: 'm10-12', brandName: 'Prolia', genericName: 'Denosumab', drugClass: 'RANKL Inhibitor', indications: ['Osteoporosis', 'Bone metastases'], commonDosing: '60 mg SC every 6 months (osteoporosis)', sideEffects: ['Hypocalcemia', 'Infections', 'ONJ', 'Rebound fracture risk on discontinuation'], keyFact: 'Do not abruptly stop; rebound vertebral fractures if discontinued' },
  { id: 'm10-13', brandName: 'Evista', genericName: 'Raloxifene', drugClass: 'Selective Estrogen Receptor Modulator (SERM)', indications: ['Osteoporosis prevention', 'Breast cancer risk reduction'], commonDosing: '60 mg PO daily', sideEffects: ['Hot flashes', 'DVT/PE', 'Leg cramps'], keyFact: 'Estrogenic on bone, anti-estrogenic on breast; increased VTE risk' },

  // 10c: Contraceptives & Hormonal Therapy
  { id: 'm10-14', brandName: 'Various (Ortho, Yaz, etc.)', genericName: 'Combined Oral Contraceptives (Ethinyl Estradiol + Progestin)', drugClass: 'Hormonal Contraceptive', indications: ['Contraception', 'Acne', 'Dysmenorrhea', 'PCOS'], commonDosing: '1 tablet PO daily (21/7 or 24/4 regimens)', sideEffects: ['VTE risk', 'Headache', 'Nausea', 'Breast tenderness'], keyFact: 'Contraindicated in smokers ≥35 yo, history of VTE, migraine with aura' },
  { id: 'm10-15', brandName: 'Depo-Provera', genericName: 'Medroxyprogesterone Acetate', drugClass: 'Progestin', indications: ['Contraception', 'Endometriosis', 'Abnormal uterine bleeding'], commonDosing: '150 mg IM every 3 months; 5-10 mg PO daily (non-contraceptive)', sideEffects: ['Weight gain', 'Irregular bleeding', 'Bone loss', 'Depression'], keyFact: 'Black box: loss of bone mineral density with long-term use; limit to 2 years' },
  { id: 'm10-16', brandName: 'Estrace/Vivelle', genericName: 'Estradiol', drugClass: 'Estrogen', indications: ['Menopausal symptoms', 'Osteoporosis prevention', 'Hypogonadism'], commonDosing: '0.5-2 mg PO daily or 0.025-0.1 mg/day patch', sideEffects: ['VTE risk', 'Breast tenderness', 'Headache', 'Endometrial hyperplasia'], keyFact: 'Transdermal preferred for lower VTE risk; always pair with progestin if uterus intact' },
  { id: 'm10-17', brandName: 'Premarin', genericName: 'Conjugated Estrogens', drugClass: 'Estrogen', indications: ['Menopausal symptoms', 'Osteoporosis', 'Vaginal atrophy'], commonDosing: '0.3-1.25 mg PO daily', sideEffects: ['VTE risk', 'Breast tenderness', 'Nausea'], keyFact: 'Derived from horse urine; add progestin if uterus intact to prevent endometrial cancer' },

  // 10d: Smoking Cessation & Dependence
  { id: 'm10-18', brandName: 'Chantix', genericName: 'Varenicline', drugClass: 'Nicotinic Receptor Partial Agonist', indications: ['Smoking cessation'], commonDosing: '0.5 mg PO daily x3d, 0.5 mg BID x4d, then 1 mg BID x11 weeks', sideEffects: ['Nausea', 'Insomnia', 'Abnormal dreams', 'Neuropsychiatric events'], keyFact: 'Most effective single agent for smoking cessation; start 1 week before quit date' },
  { id: 'm10-19', brandName: 'Nicoderm/Nicorette', genericName: 'Nicotine Replacement Therapy', drugClass: 'Nicotinic Agonist', indications: ['Smoking cessation'], commonDosing: 'Patch: 7-21 mg/day; Gum: 2-4 mg PRN; Lozenge: 2-4 mg PRN', sideEffects: ['Skin irritation (patch)', 'Jaw ache (gum)', 'Hiccups', 'N/V'], keyFact: 'Combination therapy (patch + gum/lozenge) more effective than single NRT' },

  // 10e: Eye/Ear & Misc
  { id: 'm10-20', brandName: 'Xalatan', genericName: 'Latanoprost', drugClass: 'Prostaglandin Analog (Ophthalmic)', indications: ['Open-angle glaucoma', 'Ocular hypertension'], commonDosing: '1 drop in affected eye(s) daily at bedtime', sideEffects: ['Iris color change', 'Eyelash growth', 'Conjunctival hyperemia'], keyFact: 'First-line for glaucoma; permanent iris darkening possible; store in fridge before opening' },
  { id: 'm10-21', brandName: 'Timoptic', genericName: 'Timolol (Ophthalmic)', drugClass: 'Beta Blocker (Ophthalmic)', indications: ['Open-angle glaucoma', 'Ocular hypertension'], commonDosing: '1 drop in affected eye(s) BID', sideEffects: ['Bradycardia', 'Bronchospasm', 'Fatigue'], keyFact: 'Systemic beta-blocker effects possible; avoid in asthma/COPD & bradycardia' },
  { id: 'm10-22', brandName: 'Ciprodex', genericName: 'Ciprofloxacin/Dexamethasone Otic', drugClass: 'Fluoroquinolone + Corticosteroid (Otic)', indications: ['Acute otitis externa', 'Acute otitis media with tubes'], commonDosing: '4 drops in affected ear BID x7 days', sideEffects: ['Ear discomfort', 'Pruritus', 'Superinfection'], keyFact: 'Warm drops to body temperature before instilling to reduce vertigo' },
  { id: 'm10-23', brandName: 'Restasis', genericName: 'Cyclosporine Ophthalmic', drugClass: 'Immunomodulator (Ophthalmic)', indications: ['Chronic dry eye disease'], commonDosing: '1 drop in each eye BID', sideEffects: ['Burning/stinging', 'Conjunctival hyperemia', 'Blurred vision'], keyFact: 'Takes 4-6 weeks for full effect; increases tear production by reducing inflammation' },
  { id: 'm10-24', brandName: 'Sevelamer', genericName: 'Sevelamer', drugClass: 'Phosphate Binder', indications: ['Hyperphosphatemia in CKD'], commonDosing: '800-1600 mg PO TID with meals', sideEffects: ['GI upset', 'Constipation', 'Metabolic acidosis'], keyFact: 'Non-calcium phosphate binder; must take with meals to bind dietary phosphorus' },
  { id: 'm10-25', brandName: 'Epogen/Procrit', genericName: 'Epoetin Alfa', drugClass: 'Erythropoiesis-Stimulating Agent', indications: ['Anemia of CKD', 'Chemo-induced anemia'], commonDosing: '50-300 units/kg SC/IV 3x/week', sideEffects: ['Hypertension', 'Thrombosis', 'Pure red cell aplasia'], keyFact: 'Target Hgb 10-11.5; black box for increased cancer mortality/thrombosis' },
];

export function getDrugById(id: string): Drug | undefined {
  return drugs.find(d => d.id === id);
}

export function getDrugsByIds(ids: string[]): Drug[] {
  return ids.map(id => drugs.find(d => d.id === id)).filter((d): d is Drug => d !== undefined);
}
